---
# Build context is set to repository root to access packages/ol-orchestrate-lib
directory: ../..
# The Dockerfile is located in the learning_resources directory
dockerfile: dg_projects/learning_resources/Dockerfile
registry: mitodl/dagster-learning_resources
