---
# Build context is set to repository root to access packages/ol-orchestrate-lib
directory: ../..
# The Dockerfile is located in the openedx directory
dockerfile: dg_projects/openedx/Dockerfile
registry: mitodl/dagster-openedx
