---
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'open_learning'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'open_learning'

# Load AWS credentials for DuckDB Iceberg access
on-run-start:
  - "{{ duckdb_init() }}"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
- "target"
- "dbt_packages"

dispatch:
- macro_namespace: dbt_utils
  search_order: ['trino_utils', 'dbt_utils']
- macro_namespace: dbt_date
  search_order: ['trino_utils', 'dbt_date']
- macro_namespace: metrics
  search_order: ['trino_utils', 'metrics']

vars:
  schema_suffix: dev

  open_learning:
    platforms: ['Bootcamps', 'xPro', 'xPRO Emeritus', 'xPRO Global Alumni', 'MITx
        Online', 'MicroMasters', 'edX.org', 'Residential MITx']
    bootcamps: 'Bootcamps'
    edxorg: 'edX.org'
    mitxpro: 'xPro'
    micromasters: 'MicroMasters'
    mitxonline: 'MITx Online'
    residential: 'Residential MITx'
    emeritus: 'xPRO Emeritus'
    global_alumni: 'xPRO Global Alumni'
    dedp_micromasters_program_id: 2
    dedp_mitxonline_international_development_program_id: 1
    dedp_mitxonline_public_policy_program_id: 2
    dedp_mitxonline_good_economics_for_hard_times_course_number: '14.009x'
    dedp_mitxonline_good_economics_for_hard_times_internation_development_cutoff: '2023-08-01'
    ocw_production_url: 'https://ocw.mit.edu/'
    mitxonline_openedx_url: 'https://courses.learn.mit.edu'
    mitxpro_openedx_url: 'https://courses.xpro.mit.edu'

    highest_education_values: ['Doctorate', "Master''s or professional degree", "Bachelor''s\
        \ degree", 'Associate degree', 'Secondary/high school', 'Junior secondary/junior
        high/middle school', 'Elementary/primary school', 'No formal education', 'Other
        education', "Doctorate in science or engineering", "Doctorate in another field",
      '']
    gender_values: ['Male', 'Female', 'Transgender', 'Non-binary/non-conforming',
      'Binary', 'Other/Prefer Not to Say', '']

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  open_learning:
    +properties:
      format: "'PARQUET'"
    +required_docs: true
    +grants:
      select: ['read_only_production', 'ol_data_analyst', production_analyst', 'ol_data_engineer']
      insert: ['production_analyst', 'ol_data_engineer']
      update: ['production_analyst', 'ol_data_engineer']
      delete: ['production_analyst', 'ol_data_engineer']
      all privileges: ['accountadmin', 'ol_platform_admin']
    staging:
      +materialized: table
      +schema: staging
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'reverse_etl']
    migration:
      +materialized: table
      +schema: migration
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'reverse_etl']
    dimensional:
      +materialized: table
      +schema: dimensional
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'business_intelligence',
          'ol_business_analyst', 'reverse_etl']
    intermediate:
      +materialized: table
      +schema: intermediate
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'business_intelligence',
          'ol_business_analyst', 'reverse_etl']
    marts:
      +materialized: table
      +schema: mart
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'business_intelligence',
          'ol_business_analyst', 'reverse_etl', 'finance']
    reporting:
      +materialized: table
      +schema: reporting
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'business_intelligence',
          'ol_business_analyst', 'reverse_etl']
    external:
      +materialized: table
      +schema: external
      +grants:
        select: ['read_only_production', 'ol_data_analyst', 'business_intelligence',
          'ol_business_analyst', 'reverse_etl', 'mit_irx']
    sample:


# Test severity config
# default for error_if and warn_if are !=0
tests:
  open_learning:
    +error_if: ">10"

flags:
  require_certificate_validation: true
