---
open_learning:
  target: dev_qa
  outputs:
    qa:
      type: trino
      method: ldap
      user: '{{ env_var("DBT_TRINO_USERNAME") }}'
      password: '{{ env_var("DBT_TRINO_PASSWORD") }}'
      database: ol_data_lake_qa
      port: 443
      schema: ol_warehouse_qa
      host: mitol-ol-data-lake-qa-0.trino.galaxy.starburst.io
      http_scheme: https
      threads: 4
    production:
      type: trino
      method: ldap
      user: '{{ env_var("DBT_TRINO_USERNAME") }}'
      password: '{{ env_var("DBT_TRINO_PASSWORD") }}'
      database: ol_data_lake_production
      port: 443
      schema: ol_warehouse_production
      host: mitol-ol-data-lake-production.trino.galaxy.starburst.io
      http_scheme: https
      threads: 4
    dev_qa:
      type: trino
      method: oauth
      database: ol_data_lake_qa
      port: 443
      schema: ol_warehouse_qa{{ "_{}".format(var('schema_suffix')) }}
      host: mitol-ol-data-lake-qa-0.trino.galaxy.starburst.io
      http_scheme: https
      threads: 4
    dev_production:
      type: trino
      method: oauth
      database: ol_data_lake_production
      port: 443
      schema: ol_warehouse_production{{ "_{}".format(var('schema_suffix')) }}
      host: mitol-ol-data-lake-production.trino.galaxy.starburst.io
      http_scheme: https
      threads: 4
    dev:
      type: duckdb
      path: dev_dbs/dev.duckdb
    dev_local:
      type: duckdb
      path: '{{ env_var("HOME") }}/.ol-dbt/local.duckdb'
      schema: main
      threads: 4
      use_credential_provider: aws
      extensions:
      - httpfs
      - aws
      - iceberg
      settings:
        memory_limit: '8GB'
        temp_directory: '{{ env_var("HOME") }}/.ol-dbt/temp'
        enable_http_metadata_cache: true
    dev_local_iceberg:
      type: duckdb
      path: ':memory:'
      threads: 4
      extensions:
      - httpfs
      - aws
      - iceberg
      settings:
        memory_limit: '8GB'
        temp_directory: '{{ env_var("HOME") }}/.ol-dbt/temp'
        enable_http_metadata_cache: true
        s3_region: '{{ env_var("AWS_DEFAULT_REGION", "us-east-1") }}'
        s3_access_key_id: '{{ env_var("AWS_ACCESS_KEY_ID", "") }}'
        s3_secret_access_key: '{{ env_var("AWS_SECRET_ACCESS_KEY", "") }}'
