---
open_learning:
  target: dev
  outputs:
    qa:
      type: trino
      method: ldap
      user: '{{ env_var("DBT_TRINO_USERNAME") }}'
      password: '{{ env_var("DBT_TRINO_PASSWORD") }}'
      database: ol_data_lake_qa
      port: 443
      schema: ol_warehouse_qa
      host: mitol-ol-data-lake-qa.trino.galaxy.starburst.io
      http_scheme: https
    production:
      type: trino
      method: ldap
      user: '{{ env_var("DBT_TRINO_USERNAME") }}'
      password: '{{ env_var("DBT_TRINO_PASSWORD") }}'
      database: ol_data_lake_production
      port: 443
      schema: ol_warehouse_production
      host: mitol-ol-data-lake-production.trino.galaxy.starburst.io
      http_scheme: https
