FROM python:3.9-slim

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app /tmp/packages && \
    useradd -s /bin/bash -d /opt/dagster/dagster_home/ dagster && \
    chown -R dagster:dagster /opt/dagster/dagster_home /opt/dagster/app
COPY *.whl /tmp/packages/
RUN pip install --no-cache-dir /tmp/packages/* && rm -r /tmp/packages/
COPY --chown=dagster:dagster src/ol_dbt /opt/dbt/
USER dagster
ENTRYPOINT ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000"]
