---
resources:
- name: ol-data-platform
  type: git
  icon: github
  source:
    uri: https://github.com/mitodl/ol-data-platform
    branch: elt_refactor

jobs:
- name: build-and-publish-container
  public: true
  plan:
  - get: ol-data-platform
    trigger: true
  - task: build-images
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: python
          tag: 3.9
      inputs:
      - name: ol-data-platform
      run:
        path: sh
        dir: ol-data-platform
        args:
        - -exc
        - |
          apt-get update
          apt-get install -y docker.io
          dockerd 2>&1 > /dev/null &
          ./pants --tag=docker_image package ::
