slice_name: Chatbot Usage By Type
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: activity_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: chatbot_used_count
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 2284
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(chatbot_used_count)
    optionName: metric_y2zc21f3i4_m5zfsvf6whn
    sqlExpression: null
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  showTooltipTotal: true
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  time_shift_color: true
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: chatbot_type
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 30
  y_axis_title_position: Left
query_context: null
cache_timeout: null
uuid: 751da4ab-6e41-44de-a2b8-e54dc7b2c6b0
version: 1.0.0
dataset_uuid: 8c2b6f11-28f8-4353-8e43-6c53ea6b1d91
