cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f1ec896e-86d4-451a-84cc-841d234e70a6  # int__learn_ai__chatbot
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: VideoGPTBot
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_bqsyyf0759m_oz3z7w8aqd
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: chatsession_agent
  all_columns:
  - chatsession_agent
  - chatsession_title
  - courserun_readable_id
  - chatsession_object_id
  - user_email
  - user_id
  - user_full_name
  - chatsession_thread_id
  - checkpoint_step
  - human_message
  - agent_message
  - parent_checkpoint_id
  - chatsession_created_on
  - chatsession_updated_on
  - checkpoint_metadata
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_type: values
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Chatbots
uuid: 37348ff8-4ec6-4b33-a2a6-5d8d8bf62356
version: 1.0.0
viz_type: table
