slice_name: Combined Learners
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards:
  - 11
  extra_form_data: {}
  groupby:
  - user_username
  - user_email
  - user_country_code
  - user_full_name
  order_by_cols: []
  percent_metrics: []
  query_mode: aggregate
  row_limit: 50000
  server_pagination: false
  show_cell_bars: true
  show_totals: true
  slice_id: 115
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: f2f10600-7302-4887-af04-d0aad29333ea
version: 1.0.0
dataset_uuid: 01f179b6-cb75-465f-8ceb-0525c24fa223
