slice_name: Combined Learners
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 11
  extra_form_data: {}
  groupby:
  - user_username
  - user_email
  - user_country_code
  - user_full_name
  include_search: true
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 50000
  server_page_length: 10
  server_pagination: false
  show_cell_bars: true
  show_totals: true
  slice_id: 127
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 0cf1e9cf-4645-4397-ac5a-d9a7b75d0ad5
version: 1.0.0
dataset_uuid: 01f179b6-cb75-465f-8ceb-0525c24fa223
