cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f221af29-5df4-4025-8355-401041f94835  # marts__combined_course_engagements
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerEnabled: true
  markerSize: 6
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Watched_a_video
    optionName: metric_dbwq09vzfs8_i6m93r7z48
    sqlExpression: COUNT(DISTINCT(CASE WHEN num_video_played> 0 THEN user_email ELSE
      null END))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Tried_a_problem
    optionName: metric_fc9iy7qj0ih_7iecfw62ccm
    sqlExpression: COUNT(DISTINCT (case when num_problem_submitted> 0 then user_email
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Participated_in_discussion
    optionName: metric_2gbwr6eyc6u_b9rcf5q4lf4
    sqlExpression: COUNT(DISTINCT (case when num_discussion_participated> 0 then user_email
      else null end))
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_email
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 717
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Learner_Engaged_count
    optionName: metric_h3mhtugsrtu_pfth2r3i53
    sqlExpression: null
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  rolling_type: null
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1W
  timeseries_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courseactivity_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 711
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(courseactivity_date)
    optionName: metric_nmzsule9cof_b9gtm7uul
    sqlExpression: null
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis: courseactivity_date
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
  zoomable: true
slice_name: Content Engagement
uuid: aa66927b-cc60-4950-8ad8-f79081736841
version: 1.0.0
viz_type: echarts_timeseries_line
