cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: a5df905c-0480-4227-b234-1a1064672b32  # marts__combined_discounts
description: null
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby:
  - couponpaymentversion_id
  - discount_code
  - discount_name
  - b2b_contract_number
  - discount_type
  - discount_source
  - discount_amount_text
  - company_name
  - discount_activated_on
  - discount_expires_on
  - couponpayment_name
  - redeemed
  - expressionType: SQL
    label: valid_now
    sqlExpression: "case when cast(now() as date)>=cast(substring(discount_activated_on,\
      \ 1, 10) as date) \nand cast(now() as date)<=cast(substring(discount_expires_on,\
      \ 1, 10) as date) \nthen TRUE else FALSE end"
  - expressionType: SQL
    label: total_nr_coupons
    sqlExpression: num_discount_codes*discount_max_redemptions
  - expressionType: SQL
    label: Coupons_left
    sqlExpression: (num_discount_codes*discount_max_redemptions) - discounts_used_count
  - discounts_used_count
  - b2breceipt_reference_number
  - product_readable_id
  - payment_transaction
  - discount_max_redemptions
  order_by_cols: []
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: aggregate
  row_limit: 100000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: Coupon/Discount Summary
uuid: 2e066386-dc90-48e3-859b-2b665b3cb257
version: 1.0.0
viz_type: table
