cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 50998478-4b82-451d-82ed-5ea60fd48b05  # marts__mitxpro_all_coupons
description: null
params:
  adhoc_filters: []
  all_columns:
  - couponpaymentversion_id
  - coupon_code
  - coupon_name
  - b2border_contract_number
  - coupon_type
  - discount_source
  - discount_amount
  - company_name
  - activated_on
  - expires_on
  - couponpayment_name
  - redeemed
  - datasourceWarning: false
    expressionType: SQL
    label: valid_now
    sqlExpression: "case when cast(now() as date)>=cast(substring(activated_on, 1,\
      \ 10) as date) \nand cast(now() as date)<=cast(substring(expires_on, 1, 10)\
      \ as date) \nthen TRUE else FALSE end"
  - datasourceWarning: false
    expressionType: SQL
    label: total_nr_coupons
    sqlExpression: couponpaymentversion_num_coupon_codes* couponpaymentversion_max_redemptions
  - expressionType: SQL
    label: Coupons_left
    sqlExpression: (couponpaymentversion_num_coupon_codes* couponpaymentversion_max_redemptions)
      - coupons_used_count
  - coupons_used_count
  - b2breceipt_reference_number
  - product_readable_id
  - payment_transaction
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    couponpaymentversion_id:
      showCellBars: false
    coupons_used_count:
      showCellBars: false
    total_nr_coupons:
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Coupon Summary
uuid: ae86fc71-d19e-4e6a-80b6-c68ca638b536
version: 1.0.0
viz_type: table
