cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 836dd1f0-3e2e-45a9-a721-62a471a43de8  # marts__combined_course_enrollment_detail
description: null
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards:
  - 26
  extra_form_data: {}
  groupby:
  - course_title
  - course_readable_id
  - courserun_title
  - courserun_readable_id
  - platform
  - courserun_start_on
  - courserun_end_on
  - courserun_upgrade_deadline
  - courserun_is_current
  order_by_cols: []
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Course Run Metadata
uuid: 23fb7405-da8f-4983-839d-b1d7fb07e733
version: 1.0.0
viz_type: table
