slice_name: Course to Program Reference
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby:
  - platform
  - course_title
  - course_readable_id
  - program_title
  - program_readable_id
  - program_id
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 5a5e1d10-7bbe-4329-891d-029255d6efe0
version: 1.0.0
dataset_uuid: f841a3e6-d864-4499-94dd-6ceafe8ac74f
