cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0242e111-f314-42a7-8c6b-fb4cb4084bc2  # course_staff_report
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: last_course_activity_date
  all_columns:
  - platform
  - user_username
  - user_email
  - courserun_readable_id
  - course_roles
  - courserun_start_on
  - courserun_end_on
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: raw
  row_limit: 500000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    last_course_activity_date: true
  viz_type: table
slice_name: Course Staff and Admins
uuid: fec6f1a5-8a3c-4bf3-9a1a-5ec25598502b
version: 1.0.0
viz_type: table
