slice_name: Course Run Metadata
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  annotation_layers: []
  color_pn: true
  comparison_type: values
  dashboards:
  - 16
  - 24
  extra_form_data: {}
  groupby:
  - course_title
  - course_readable_id
  - courserun_title
  - courserun_readable_id
  - platform
  - courserun_start_on
  - courserun_end_on
  - courserun_upgrade_deadline
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  show_cell_bars: true
  slice_id: 35
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 01f0a8ee-45f0-40ef-a96e-250a40aebf10
version: 1.0.0
dataset_uuid: 836dd1f0-3e2e-45a9-a721-62a471a43de8
