slice_name: Course Run Metadata
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  comparison_type: values
  dashboards:
  - 16
  - 24
  extra_form_data: {}
  groupby:
  - course_title
  - course_readable_id
  - courserun_title
  - courserun_readable_id
  - platform
  - courserun_start_on
  - courserun_end_on
  - courserun_upgrade_deadline
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  show_cell_bars: true
  slice_id: 35
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: c6e47f3c-aeb2-4e25-bf43-e9bd3f068127
version: 1.0.0
dataset_uuid: f3e517dd-4012-441e-8dfe-edaef1318000
