cache_timeout: -1
certification_details: null
certified_by: null
dataset_uuid: b1f7c663-9faf-4c95-bdeb-d786a3f4cd3c  # chatbot_usage_report
description: null
params:
  adhoc_filters: []
  all_columns:
  - ai_agent
  - resource_id
  - thread_id
  - human_message
  - ai_message
  - created_on
  - message_index
  allow_render_html: false
  color_pn: false
  column_config:
    message_index:
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  order_by_cols:
  - '["created_on", false]'
  - '["message_index", true]'
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  server_page_length: 10
  show_cell_bars: false
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Course AI Chatbot
uuid: 92488983-505d-4642-a76d-6d5225275577
version: 1.0.0
viz_type: table
