cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 811f8301-4bea-461e-8359-d354af75c4b1  # marts__mitxonline_course_enrollments
description: null
params:
  adhoc_filters: []
  all_columns: []
  annotation_layers: []
  color_pn: true
  comparison_type: values
  extra_form_data: {}
  groupby:
  - courserun_readable_id
  - courserun_title
  - course_number
  - user_full_name
  - user_email
  - program_title
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: course_user_mapping
uuid: 08141743-0bc0-4a79-a3b4-39d34d221742
version: 1.0.0
viz_type: table
