slice_name: Course AI Chatbot (Deprecated)
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_s4j4p8aqwz_qj2vtbjwpw
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: (agent_message IS NOT NULL AND agent_message != '' OR human_message IS NOT NULL)
    subject: null
  all_columns:
  - expressionType: SQL
    label: ai_tool
    sqlExpression: chatsession_agent
  - expressionType: SQL
    label: resource_id
    sqlExpression: chatsession_object_id
  - expressionType: SQL
    label: thread_id
    sqlExpression: chatsession_thread_id
  - human_message
  - agent_message
  - expressionType: SQL
    label: created_on
    sqlExpression: chatsession_created_on
  allow_render_html: true
  color_pn: true
  column_config:
    user_id:
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 55
  extra_form_data: {}
  groupby: []
  order_by_cols:
  - '["chatsession_thread_id", true]'
  - '["checkpoint_step", true]'
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 126
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 148f6894-7e0b-4750-aef4-501db89a4543
version: 1.0.0
dataset_uuid: f1ec896e-86d4-451a-84cc-841d234e70a6
