cache_timeout: null
certification_details: null
certified_by: null
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Verified_Count
    optionName: metric_sro1akhey7m_2hewdplnpqn
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'verified' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Audit_Count
    optionName: metric_h6b5qcemebr_cgvckf11ndw
    sqlExpression: 'sum(case when courserunenrollment_enrollment_mode= ''audit'' then
      1 else 0 end) '
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Total_Enrollment_count
    optionName: metric_non11autol_nyiwujsq2rq
    sqlExpression: count(*)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  rolling_type: null
  row_limit: 10000
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis:
    expressionType: SQL
    label: Enrollment_Date
    sqlExpression: cast(substring(courserunenrollment_created_on, 1, 10) as date)
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: Daily Learner Enrollment- All Courses
uuid: 65762bf7-1c08-4abb-ad17-e569311a67d0
version: 1.0.0
viz_type: echarts_timeseries_bar
