cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 2a608e5d-c828-4457-83c2-0912a1534430  # tfact_video_events
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - video_duration
  - video_position
  - video_name
  - event_timestamp
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: '500000'
  show_cell_bars: false
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  viz_type: table
slice_name: Data Detail Video
uuid: 8cd66663-f93f-4751-be11-14c5d4c28ed5
version: 1.0.0
viz_type: table
