cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: dc0886e8-1861-4bd9-a694-25a063adcf83  # data_detail_problems
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - problem_name
  - event_type
  - answers
  - attempt
  - success
  - grade
  - max_grade
  - max_attempts
  - weight
  - markdown
  - event_timestamp
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby: []
  metrics: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  time_grain_sqla: P1D
  viz_type: table
slice_name: Data Detail Problems
uuid: 5e8a4f03-1504-4f8b-9990-de300d73ff93
version: 1.0.0
viz_type: table
