slice_name: Data Detail Discussion
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - post_title
  - post_content
  - discussion_component_name
  - page_url
  - event_timestamp
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby: []
  metrics: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  time_grain_sqla: P1D
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 39c99c2d-1290-4d37-9b0f-eef559172947
version: 1.0.0
dataset_uuid: 5bab95fd-d465-44f3-bed8-40c559958fc4
