cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 2e7e66d9-731a-405a-8605-660304ab7540  # data_detail_nav
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - starting_position
  - ending_position
  - event_timestamp
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  viz_type: table
slice_name: Data Detail Navigation
uuid: cf8305f6-fe5d-4791-8185-3051b76f4738
version: 1.0.0
viz_type: table
