slice_name: Data Detail Navigation
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - starting_position
  - ending_position
  - event_timestamp
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby: []
  metrics: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 105
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  time_grain_sqla: P1D
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: cf8305f6-fe5d-4791-8185-3051b76f4738
version: 1.0.0
dataset_uuid: 2189d254-14fd-4b38-85a8-6af918546dd0
