cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: ec0fc17c-ebca-44ae-94ae-2072da856d24  # discussion_detail_report
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: event_timestamp
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - post_title
  - post_content
  - discussion_component_name
  - page_url
  - event_timestamp
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    event_timestamp: true
  viz_type: table
slice_name: Data Detail Discussion
uuid: 39c99c2d-1290-4d37-9b0f-eef559172947
version: 1.0.0
viz_type: table
