cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 70bc54c5-1073-4bdc-922b-76f6eff82ae3  # marts__micromasters_course_certificates
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - '1'
    - '2'
    - '3'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_gpq16kei9r_aisn0rg4uqe
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: mitxonline_program_id
  - clause: WHERE
    comparator: '%3T2023%'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_eqdwy3pmq3j_tjz10zbhiw
    isExtra: false
    isNew: false
    operator: LIKE
    operatorId: LIKE
    sqlExpression: null
    subject: courserun_readable_id
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: count(*)
    optionName: metric_lg43l93lbdj_bv8ubegsyx
    sqlExpression: count(*)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: courserun_readable_id
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: DEDP 3T2023 certificates by course runs
uuid: 092c45b2-f7d3-4c7e-b4aa-99890c07746a
version: 1.0.0
viz_type: echarts_timeseries_bar
