cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 70bc54c5-1073-4bdc-922b-76f6eff82ae3  # marts__micromasters_course_certificates
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - '1'
    - '2'
    - '3'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_zqjkwpt3r4_4750osikwqg
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: mitxonline_program_id
  all_columns: []
  annotation_layers: []
  color_pn: true
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby:
  - user_email
  - courserun_readable_id
  - grade
  metrics: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: DEDP Learner Grades by Course
uuid: 1ec63597-fd4e-4e55-b5e0-aa09309f3cce
version: 1.0.0
viz_type: table
