slice_name: DEDP Financial Assistance - Income < $10000
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 211__table
  viz_type: table
  slice_id: 178
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 3
  matrixify_cell_title_template: ''
  query_mode: raw
  groupby: []
  temporal_columns_lookup: {}
  all_columns:
  - user_email
  - user_full_name
  - user_id
  - flexiblepriceapplication_income_usd
  - flexiblepriceapplication_original_currency
  - flexiblepriceapplication_original_income
  - flexiblepriceapplication_status
  - flexiblepriceapplication_exchange_rate_timestamp
  - flexiblepriceapplication_created_on
  - flexiblepriceapplication_updated_on
  percent_metrics: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: courserunenrollment_is_active
    operator: IS TRUE
    operatorId: IS_TRUE
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_njl872f37oo_04t3n9ipx359
  - expressionType: SIMPLE
    subject: mitxonline_program_id
    operator: IN
    operatorId: IN
    comparator:
    - 2
    - 1
    - 3
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_x0vpi9g4pcg_kxu1zx8q6j
  - expressionType: SIMPLE
    subject: flexiblepriceapplication_status
    operator: IN
    operatorId: IN
    comparator:
    - approved
    - auto-approved
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_qxq3m5tz37_nykaxn4qv4d
  - expressionType: SIMPLE
    subject: flexiblepriceapplication_income_usd
    operator: <
    operatorId: LESS_THAN
    comparator: 10000
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_ckga8a1qqdl_lg989eu83ae
  - expressionType: SQL
    sqlExpression: cast(substring(courserun_start_on, 1, 10) as date) <= current_date
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_jmqrmca0mf_brwsyv7oa87
  - expressionType: SQL
    sqlExpression: cast(substring(courserun_end_on, 1, 10) as date) > current_date
    clause: WHERE
    subject: null
    operator: null
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_0jclpvkjr3no_dxguh3dbmdm
  - expressionType: SIMPLE
    subject: user_latest_row_desc
    operator: ==
    operatorId: EQUALS
    comparator: 1
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_msnn1ddp2x_gfdp2ehbctk
  order_by_cols: []
  server_pagination: false
  row_limit: 10000
  show_totals: false
  table_timestamp_format: smart_date
  include_search: false
  allow_rearrange_columns: false
  allow_render_html: true
  show_cell_bars: false
  align_pn: false
  color_pn: true
  comparison_color_enabled: false
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":211,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courserunenrollment_is_active","op":"IS
  TRUE"},{"col":"mitxonline_program_id","op":"IN","val":[2,1,3]},{"col":"flexiblepriceapplication_status","op":"IN","val":["approved","auto-approved"]},{"col":"flexiblepriceapplication_income_usd","op":"<","val":10000},{"col":"user_latest_row_desc","op":"==","val":1}],"extras":{"having":"","where":"(cast(substring(courserun_start_on,
  1, 10) as date) <= current_date) AND (cast(substring(courserun_end_on, 1, 10) as
  date) > current_date)"},"applied_time_extras":{},"columns":["user_email","user_full_name","user_id","flexiblepriceapplication_income_usd","flexiblepriceapplication_original_currency","flexiblepriceapplication_original_income","flexiblepriceapplication_status","flexiblepriceapplication_exchange_rate_timestamp","flexiblepriceapplication_created_on","flexiblepriceapplication_updated_on"],"orderby":[],"annotation_layers":[],"row_limit":10000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"211__table","viz_type":"table","slice_id":178,"matrixify_enable":false,"matrixify_mode_columns":"disabled","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_all_sort_by_columns":"a_to_z","matrixify_topn_order_columns":true,"matrixify_show_column_headers":true,"matrixify_fit_columns_dynamically":true,"matrixify_mode_rows":"disabled","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_all_sort_by_rows":"a_to_z","matrixify_topn_order_rows":true,"matrixify_show_row_labels":true,"matrixify_row_height":300,"matrixify_charts_per_row":3,"matrixify_cell_title_template":"","query_mode":"raw","groupby":[],"temporal_columns_lookup":{},"all_columns":["user_email","user_full_name","user_id","flexiblepriceapplication_income_usd","flexiblepriceapplication_original_currency","flexiblepriceapplication_original_income","flexiblepriceapplication_status","flexiblepriceapplication_exchange_rate_timestamp","flexiblepriceapplication_created_on","flexiblepriceapplication_updated_on"],"percent_metrics":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"courserunenrollment_is_active","operator":"IS
  TRUE","operatorId":"IS_TRUE","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_njl872f37oo_04t3n9ipx359"},{"expressionType":"SIMPLE","subject":"mitxonline_program_id","operator":"IN","operatorId":"IN","comparator":[2,1,3],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_x0vpi9g4pcg_kxu1zx8q6j"},{"expressionType":"SIMPLE","subject":"flexiblepriceapplication_status","operator":"IN","operatorId":"IN","comparator":["approved","auto-approved"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_qxq3m5tz37_nykaxn4qv4d"},{"expressionType":"SIMPLE","subject":"flexiblepriceapplication_income_usd","operator":"<","operatorId":"LESS_THAN","comparator":10000,"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_ckga8a1qqdl_lg989eu83ae"},{"expressionType":"SQL","sqlExpression":"cast(substring(courserun_start_on,
  1, 10) as date) <= current_date","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_jmqrmca0mf_brwsyv7oa87"},{"expressionType":"SQL","sqlExpression":"cast(substring(courserun_end_on,
  1, 10) as date) > current_date","clause":"WHERE","subject":null,"operator":null,"comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_0jclpvkjr3no_dxguh3dbmdm"},{"expressionType":"SIMPLE","subject":"user_latest_row_desc","operator":"==","operatorId":"EQUALS","comparator":1,"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_msnn1ddp2x_gfdp2ehbctk"}],"order_by_cols":[],"server_pagination":false,"row_limit":10000,"show_totals":false,"table_timestamp_format":"smart_date","include_search":false,"allow_rearrange_columns":false,"allow_render_html":true,"show_cell_bars":false,"align_pn":false,"color_pn":true,"comparison_color_enabled":false,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9d893168-08b9-4afd-8ed6-0a82dd87a17c
version: 1.0.0
dataset_uuid: 29720b2d-fac5-44a0-88dd-b2cbed0482ba
