cache_timeout: -1
certification_details: null
certified_by: null
dataset_uuid: 3b10e411-e497-4e8c-8132-08f673e8d72d  # tables
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_i5ds8ytwl4_d2fzal40y7m
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: created_on
  - clause: WHERE
    comparator:
    - dim_user
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_q4riaven7_8onmwm8kec9
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: table_name
  all_columns:
  - expressionType: SQL
    label: last_updated_on in UTC
    sqlExpression: changed_on
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    changed_on: true
    created_on: true
  viz_type: table
slice_name: dim_user last updated
uuid: 1e1419f1-f836-43de-964e-6ea9d9521645
version: 1.0.0
viz_type: table
