cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: a7af739c-62dd-4be0-a46f-5771a7e0c466  # marts__combined_video_engagements
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_email
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 652
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_nm46la8oog_g7874if5427
    sqlExpression: null
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: user_watched_video_count
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: Distribution of Number of Videos Watched
uuid: 9bdb6168-d5c9-4651-af36-556e29f3b5db
version: 1.0.0
viz_type: echarts_timeseries_bar
