cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f221af29-5df4-4025-8355-401041f94835  # marts__combined_course_engagements
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 26
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendMargin: null
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Watched_a_video
    optionName: metric_059piu499ctj_v1biwm6w8a
    sqlExpression: COUNT(DISTINCT(CASE WHEN num_video_played> 0 THEN user_username
      ELSE null END))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Tried_a_problem
    optionName: metric_t4xk2kk9zxa_zdkc9h1us7h
    sqlExpression: COUNT(DISTINCT(case when num_problem_submitted> 0 then user_username
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Participated_In_Discussion
    optionName: metric_8zaqrr5aljx_o1deaowi9rp
    sqlExpression: COUNT(DISTINCT(case when num_discussion_participated> 0 then user_username
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_653jots7vt7_l91azd98z0k
    sqlExpression: COUNT(DISTINCT user_username)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  showTooltipPercentage: false
  showTooltipTotal: false
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: courserun_readable_id
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: Engagement Totals
uuid: 24ea41c4-da94-443a-af6b-77bc7e09c303
version: 1.0.0
viz_type: echarts_timeseries_bar
