cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 836dd1f0-3e2e-45a9-a721-62a471a43de8  # marts__combined_course_enrollment_detail
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: activity_date
  annotation_layers: []
  color_by: metric
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  country_fieldtype: cca2
  entity: user_country_code
  extra_form_data: {}
  linear_color_scheme: superset_seq_1
  max_bubble_size: '25'
  metric:
    aggregate: SUM
    column:
      advanced_data_type: null
      changed_on: '2024-07-25T21:48:03.649184'
      column_name: enrollment_count
      created_on: '2024-07-25T21:48:03.649180'
      description: null
      expression: null
      extra: '{}'
      filterable: true
      groupby: true
      id: 564
      is_active: true
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      uuid: 79e79859-63da-475b-9eb6-b5a577b8faf4
      verbose_name: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: enrollment_count
    optionName: metric_qhdthmpen3_n09pia9r95s
    sqlExpression: null
  row_limit: 10000
  viz_type: world_map
  y_axis_format: SMART_NUMBER
slice_name: Enrollment Geography
uuid: 118ba89d-4c33-4720-b22e-a2576ff93316
version: 1.0.0
viz_type: world_map
