cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 01f179b6-cb75-465f-8ceb-0525c24fa223  # enrollment_detail_report
description: null
params:
  adhoc_filters: []
  align_pn: false
  all_columns:
  - platform
  - user_email
  - user_full_name
  - courserun_readable_id
  - courserun_title
  - courserun_start_on
  - courserun_end_on
  - order_id
  - courserunenrollment_id
  - program_name
  - courserunenrollment_enrollment_mode
  - courserunenrollment_created_on
  - courserunenrollment_enrollment_status
  - courserunenrollment_is_active
  - courserunenrollment_upgraded_on
  - courserungrade_grade
  - courserungrade_is_passing
  - courseruncertificate_is_earned
  - courseruncertificate_created_on
  - courseruncertificate_url
  - order_reference_number
  - receipt_payment_timestamp
  - receipt_payer_email
  - receipt_payment_method
  - receipt_payment_amount
  - coupon_code
  - coupon_name
  - unit_price
  - discount
  - order_state
  - receipt_url
  - user_username
  - user_country_code
  - organization_name
  - redeemed_email
  allow_rearrange_columns: false
  allow_render_html: true
  color_pn: false
  column_config:
    courserunenrollment_id:
      showCellBars: false
    courserungrade_grade:
      showCellBars: false
    order_id:
      showCellBars: false
    receipt_payment_amount:
      showCellBars: false
    unit_price:
      showCellBars: false
  comparison_color_enabled: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  matrixify_all_sort_by_columns: a_to_z
  matrixify_all_sort_by_rows: a_to_z
  matrixify_cell_title_template: ''
  matrixify_charts_per_row: 3
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_selection_mode_rows: members
  matrixify_enable: false
  matrixify_fit_columns_dynamically: true
  matrixify_mode_columns: disabled
  matrixify_mode_rows: disabled
  matrixify_row_height: 300
  matrixify_show_column_headers: true
  matrixify_show_row_labels: true
  matrixify_topn_order_columns: true
  matrixify_topn_order_rows: true
  matrixify_topn_value_columns: 10
  matrixify_topn_value_rows: 10
  order_by_cols: []
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  server_pagination: false
  show_cell_bars: true
  show_totals: false
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Enrollment Detail
uuid: 1cf394ec-8561-4b0d-9d9b-f394a6029b33
version: 1.0.0
viz_type: table
