slice_name: Latest Course Activity Date
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_3bhylqb5grn_ztmh2j2v29e
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: courseactivity_date
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_1sdhhe17e5o_0lz20p68pjqs
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: courseactivity_date <= current_date
    subject: courseactivity_date
  all_columns: []
  color_pn: true
  comparison_type: values
  dashboards:
  - 27
  extra_form_data: {}
  groupby: []
  metrics:
  - aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courseactivity_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 711
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Latest Course Activity Date
    optionName: metric_2a0s7ht5t42_y116rfrjcu
    sqlExpression: null
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 62
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    courseactivity_date: true
  time_grain_sqla: P1D
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 5f95a268-4339-4d73-b8d8-d082ca53b28d
version: 1.0.0
dataset_uuid: f221af29-5df4-4025-8355-401041f94835
