slice_name: Learn User Profile
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_6kj0gtlj4vo_wgmlznswubf
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: mitlearn_user_id
  all_columns:
  - user_global_id
  - mitlearn_user_id
  - email
  - full_name
  - highest_education
  - topic_interests
  - goals
  - certificate_desired
  - delivery_preference
  - completed_onboarding
  - user_joined_on_mitlearn
  - user_is_active_on_mitlearn
  allow_rearrange_columns: true
  allow_render_html: false
  color_pn: false
  column_config:
    goals:
      horizontalAlign: left
      truncateLongCells: false
    mitlearn_user_id:
      horizontalAlign: left
      showCellBars: false
    topic_interests:
      columnWidth: null
      horizontalAlign: left
      truncateLongCells: false
  conditional_formatting: []
  dashboards:
  - 49
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols:
  - '["user_joined_on_mitlearn", false]'
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  show_cell_bars: true
  slice_id: 123
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 2e3e900a-3782-4738-80fe-0d60802d4461
version: 1.0.0
dataset_uuid: 7f46cdba-1bf0-4f10-9606-a41b77b9e77c
