cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 7f46cdba-1bf0-4f10-9606-a41b77b9e77c  # dim_user
description: null
params:
  adhoc_filters:
  - clause: WHERE
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_6kj0gtlj4vo_wgmlznswubf
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: mitlearn_user_id
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date_joined_on_mitlearn
  all_columns:
  - email
  - full_name
  - user_global_id
  - mitlearn_user_id
  - highest_education
  - topic_interests
  - goals
  - certificate_desired
  - delivery_preference
  - completed_onboarding
  - user_joined_on_mitlearn
  - user_is_active_on_mitlearn
  - user_mitxonline_username
  - user_joined_on_mitxonline
  allow_rearrange_columns: true
  allow_render_html: false
  color_pn: false
  column_config:
    goals:
      horizontalAlign: left
      truncateLongCells: false
    mitlearn_user_id:
      horizontalAlign: left
      showCellBars: false
    topic_interests:
      columnWidth: null
      horizontalAlign: left
      truncateLongCells: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols:
  - '["user_joined_on_mitlearn", false]'
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    date_joined_on_mitlearn: true
  viz_type: table
slice_name: Learn User Profile
uuid: 2e3e900a-3782-4738-80fe-0d60802d4461
version: 1.0.0
viz_type: table
