cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 836dd1f0-3e2e-45a9-a721-62a471a43de8  # marts__combined_course_enrollment_detail
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - deferred
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_3i1o0x2uzfr_kgx5rxk1vf
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: courserunenrollment_enrollment_status
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  groupby:
  - platform
  - course_title
  - courserun_readable_id
  - courserun_start_on
  - user_email
  - courserunenrollment_enrollment_status
  - courserun_is_current
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Learner Deferred Report
uuid: 5ce15be9-994b-4377-8c99-21d35267a2dd
version: 1.0.0
viz_type: table
