cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 4752cd11-a13e-4a8e-be31-4d9227b07ca2  # learner_engagement_report
description: null
params:
  adhoc_filters: []
  all_columns:
  - user_email
  - course_title
  - courserun_readable_id
  - section_title
  - subsection_title
  - expressionType: SQL
    label: Percent_Watched
    sqlExpression: case when estimated_time_played < 0 then null when estimated_time_played>=video_duration
      then 1 when (video_duration is null or video_duration= 0 or estimated_time_played
      is null) then null else estimated_time_played/video_duration end
  - expressionType: SQL
    label: estimated_time_played(seconds)
    sqlExpression: case when estimated_time_played < 0 then null when estimated_time_played
      > video_duration then cast(video_duration as int) else cast(estimated_time_played
      as int) end
  - datasourceWarning: false
    expressionType: SQL
    label: video_duration(seconds)
    sqlExpression: cast(video_duration as int)
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    Percent_Watched:
      d3NumberFormat: ',.1%'
    estimated_time_played(seconds):
      showCellBars: false
    video_duration(seconds):
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 45
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 10000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Learner Video Engagement
uuid: 3c5fdc59-85d7-484b-9fdf-170336c8a4c0
version: 1.0.0
viz_type: table
