cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f221af29-5df4-4025-8355-401041f94835  # marts__combined_course_engagements
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_522x27a4t7w_cwj5z8kc6m
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: courseactivity_date
  all_columns:
  - user_full_name
  - user_email
  - courserun_readable_id
  - courseactivity_date
  - num_events
  - num_problem_submitted
  - num_video_played
  - num_discussion_participated
  allow_render_html: false
  annotation_layers: []
  color_pn: false
  comparison_color_scheme: Green
  conditional_formatting: []
  extra_form_data: {}
  groupby:
  - platform
  - user_username
  - courserun_readable_id
  - num_events
  - num_problem_submitted
  - num_video_played
  - num_discussion_participated
  - courseactivity_date
  order_by_cols:
  - '["courseactivity_date", false]'
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  server_pagination: false
  show_cell_bars: false
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    courseactivity_date: true
  time_grain_sqla: P1D
  viz_type: table
slice_name: Learner Course Engagement
uuid: 6df62a4b-28e2-4d78-9e22-e3dfb56fd96a
version: 1.0.0
viz_type: table
