slice_name: Learner Page Engagement
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - user_email
  - full_name
  - platform
  - course_title
  - courserun_readable_id
  - section_title
  - subsection_title
  - unit_title
  - page_viewed_title
  - num_of_page_views
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  dashboards:
  - 45
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  show_cell_bars: true
  slice_id: 94
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 9bd2269c-fd5c-463d-b63e-14fa63e90a55
version: 1.0.0
dataset_uuid: 4752cd11-a13e-4a8e-be31-4d9227b07ca2
