cache_timeout: null
certification_details: null
certified_by: null
description: null
params:
  adhoc_filters: []
  all_columns: []
  color_pn: true
  comparison_type: values
  datasource: 23__table
  extra_form_data: {}
  groupby:
  - user_id
  - user_username
  - user_email
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: Micromasters Users
uuid: d7f0a985-f4b0-4643-9832-88d106aa087c
version: 1.0.0
viz_type: table
