cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 45f0412f-0d34-4d04-a3ff-e595a3bada19  # marts__mitxonline_course_certificates
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 7
  - 20
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Certificate_count
    optionName: metric_v39mqis8me8_uw74ltnpo5q
    sqlExpression: count(*)
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_line
  x_axis:
    expressionType: SQL
    label: courseruncertificate_created_on
    sqlExpression: cast(substring(courseruncertificate_created_on, 1, 10) as date)
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
  zoomable: true
slice_name: MITxOnline Earned Certificate
uuid: d953e953-a5d6-4e48-af54-5b0e033a401c
version: 1.0.0
viz_type: echarts_timeseries_line
