cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: e7330108-bdfa-4ff0-8ca3-084d7e8cbda8  # marts__mitxonline_course_engagements_daily
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  all_columns: []
  annotation_layers: []
  color_pn: true
  comparison_type: values
  dashboards:
  - 16
  extra_form_data: {}
  groupby:
  - course_number
  - courserun_title
  - courserun_readable_id
  - courserun_start_on
  - courserun_end_on
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    courseactivity_date: true
  time_grain_sqla: P1D
  viz_type: table
slice_name: MITx Online Course Run Metadata
uuid: c46d73a1-16c3-450b-a43d-63383fad7be2
version: 1.0.0
viz_type: table
