cache_timeout: null
certification_details: null
certified_by: null
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 5
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: verified_count
    optionName: metric_n2jmx6hwai_dppg711uhn6
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'verified' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: audit_count
    optionName: metric_h6yl06zrsvi_ioalqftnb9s
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'audit' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: total_enrollment_count
    optionName: metric_yd4mcqx26io_cz6zy2hssf5
    sqlExpression: count(*)
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  rolling_type: cumsum
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  timeseries_limit_metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: MIN(courserunenrollment_created_on)
    optionName: metric_q5qzyqzlh4b_a14q0ei293
    sqlExpression: MIN(courserunenrollment_created_on)
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_area
  x_axis:
    expressionType: SQL
    label: enrollment_date
    sqlExpression: cast(substring(courserunenrollment_created_on, 1, 10) as date)
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: MITxOnline Enrollment Activity
uuid: 6fd11c69-4110-465f-8ed6-bfcdbe59b8b4
version: 1.0.0
viz_type: echarts_area
