cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 811f8301-4bea-461e-8359-d354af75c4b1  # marts__mitxonline_course_enrollments
description: null
params:
  adhoc_filters: []
  all_columns: []
  annotation_layers: []
  color_pn: true
  comparison_type: values
  extra_form_data: {}
  groupby:
  - courserun_title
  - courserun_readable_id
  - user_username
  - user_email
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: MITx Enrollments
uuid: 89862956-6021-420f-b56e-cd73e6680a78
version: 1.0.0
viz_type: table
