cache_timeout: null
certification_details: null
certified_by: null
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: learner_count
    optionName: metric_muwm1y78tg_p4be5vupx5d
    sqlExpression: count(*)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: user_highest_education
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
slice_name: MITxOnline Enrollment Demographics by Education
uuid: 5cfc7ea9-6636-41b4-9af7-68c98aeff4de
version: 1.0.0
viz_type: echarts_timeseries_bar
