cache_timeout: null
certification_details: null
certified_by: null
description: null
params:
  adhoc_filters: []
  color_by: metric
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  color_scheme: supersetColors
  country_fieldtype: cca2
  entity: user_address_country
  extra_form_data: {}
  linear_color_scheme: superset_seq_1
  max_bubble_size: '25'
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Enrollment_count
    optionName: metric_cv1tgoykxs_dwk8dh8h8ew
    sqlExpression: count(*)
  row_limit: 10000
  viz_type: world_map
  y_axis_format: SMART_NUMBER
slice_name: MITxOnline Enrollment Geography
uuid: de62ba2c-c4c8-4973-99eb-f1a7bcbe16e6
version: 1.0.0
viz_type: world_map
