cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 2f64a0b1-a1d4-4dec-95c3-7978296a3555  # marts__combined__orders
description: null
params:
  adhoc_filters: []
  align_pn: false
  all_columns:
  - platform
  - user_email
  - user_id
  - order_id
  - product_type
  - product_readable_id
  - order_created_on
  - order_created_date
  - order_state
  - unit_price
  - discount
  - order_total_price_paid
  - order_tax_amount
  - order_total_price_paid_plus_tax
  - receipt_payment_amount
  - coupon_code
  - coupon_name
  - coupon_type
  - coupon_redeemed_on
  - receipt_payer_name
  - receipt_payer_email
  - receipt_payment_card_type
  - receipt_bill_to_address_state
  - receipt_payment_method
  - order_tax_country_code
  - order_tax_rate_name
  - receipt_authorization_code
  - receipt_payment_card_number
  - receipt_payment_currency
  - product_id
  - line_id
  - receipt_payment_timestamp
  - order_reference_number
  - receipt_payer_ip_address
  - receipt_transaction_id
  - b2border_contract_number
  - order_type
  - redeemed_email
  allow_rearrange_columns: true
  allow_render_html: true
  color_pn: false
  column_config:
    discount:
      horizontalAlign: right
      truncateLongCells: true
    line_id:
      showCellBars: false
    order_id:
      showCellBars: false
    order_tax_amount:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      truncateLongCells: true
    order_total_price_paid:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      showCellBars: false
    order_total_price_paid_plus_tax:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      showCellBars: false
    receipt_payment_amount:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      truncateLongCells: false
    unit_price:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      showCellBars: false
  comparison_color_enabled: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  matrixify_all_sort_by_columns: a_to_z
  matrixify_all_sort_by_rows: a_to_z
  matrixify_cell_title_template: ''
  matrixify_charts_per_row: 3
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_selection_mode_rows: members
  matrixify_enable: false
  matrixify_fit_columns_dynamically: true
  matrixify_mode_columns: disabled
  matrixify_mode_rows: disabled
  matrixify_row_height: 300
  matrixify_show_column_headers: true
  matrixify_show_row_labels: true
  matrixify_topn_order_columns: true
  matrixify_topn_order_rows: true
  matrixify_topn_value_columns: 10
  matrixify_topn_value_rows: 10
  order_by_cols:
  - '["order_state", true]'
  - '["order_created_on", false]'
  - '["order_tax_amount", false]'
  order_desc: true
  percent_metric_calculation: row_limit
  percent_metrics: []
  query_mode: raw
  row_limit: 100000
  server_page_length: 10
  server_pagination: false
  show_cell_bars: false
  show_totals: false
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Order detail
uuid: fb906f1f-c07f-472f-9387-ad02f73cae55
version: 1.0.0
viz_type: table
