slice_name: Order detail
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 158__table
  viz_type: table
  slice_id: 230
  query_mode: raw
  groupby: []
  temporal_columns_lookup: {}
  all_columns:
  - platform
  - user_email
  - user_id
  - order_id
  - product_type
  - product_readable_id
  - order_created_on
  - order_created_date
  - order_state
  - unit_price
  - discount
  - order_tax_amount
  - order_total_price_paid_plus_tax
  - receipt_payment_amount
  - coupon_type
  - coupon_name
  - order_total_price_paid
  - receipt_payer_name
  - receipt_payer_email
  - receipt_bill_to_address_state
  - receipt_payment_card_type
  - receipt_payment_method
  - order_tax_rate_name
  - receipt_authorization_code
  - order_tax_country_code
  - receipt_payment_card_number
  - receipt_payment_currency
  - product_id
  - line_id
  - receipt_payment_timestamp
  - order_reference_number
  - coupon_redeemed_on
  - receipt_transaction_id
  - receipt_payer_ip_address
  - b2border_contract_number
  - order_type
  - redeemed_email
  percent_metrics: []
  adhoc_filters: []
  order_by_cols:
  - '["order_state", true]'
  - '["order_created_on", false]'
  - '["order_tax_amount", false]'
  order_desc: true
  server_pagination: false
  server_page_length: 10
  row_limit: 50000
  percent_metric_calculation: row_limit
  table_timestamp_format: smart_date
  include_search: true
  allow_rearrange_columns: true
  allow_render_html: true
  column_config:
    discount:
      horizontalAlign: right
      truncateLongCells: true
    line_id:
      showCellBars: false
    order_id:
      showCellBars: false
    order_tax_amount:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      truncateLongCells: true
    order_total_price_paid:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      showCellBars: false
    order_total_price_paid_plus_tax:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      showCellBars: false
    receipt_payment_amount:
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      truncateLongCells: false
    unit_price:
      currencyFormat: {}
      d3NumberFormat: ',.2f'
      d3SmallNumberFormat: ',.2f'
      horizontalAlign: right
      showCellBars: false
  show_cell_bars: false
  color_pn: false
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 33
query_context: '{"datasource":{"id":158,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["platform","user_email","user_id","order_id","product_type","product_readable_id","order_created_on","order_created_date","order_state","unit_price","discount","order_tax_amount","order_total_price_paid_plus_tax","receipt_payment_amount","coupon_type","coupon_name","order_total_price_paid","receipt_payer_name","receipt_payer_email","receipt_bill_to_address_state","receipt_payment_card_type","receipt_payment_method","order_tax_rate_name","receipt_authorization_code","order_tax_country_code","receipt_payment_card_number","receipt_payment_currency","product_id","line_id","receipt_payment_timestamp","order_reference_number","coupon_redeemed_on","receipt_transaction_id","receipt_payer_ip_address","b2border_contract_number","order_type","redeemed_email"],"orderby":[["order_state",true],["order_created_on",false],["order_tax_amount",false]],"annotation_layers":[],"row_limit":50000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"158__table","viz_type":"table","slice_id":230,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{},"all_columns":["platform","user_email","user_id","order_id","product_type","product_readable_id","order_created_on","order_created_date","order_state","unit_price","discount","order_tax_amount","order_total_price_paid_plus_tax","receipt_payment_amount","coupon_type","coupon_name","order_total_price_paid","receipt_payer_name","receipt_payer_email","receipt_bill_to_address_state","receipt_payment_card_type","receipt_payment_method","order_tax_rate_name","receipt_authorization_code","order_tax_country_code","receipt_payment_card_number","receipt_payment_currency","product_id","line_id","receipt_payment_timestamp","order_reference_number","coupon_redeemed_on","receipt_transaction_id","receipt_payer_ip_address","b2border_contract_number","order_type","redeemed_email"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":["[\"order_state\",
  true]","[\"order_created_on\", false]","[\"order_tax_amount\", false]"],"order_desc":true,"server_pagination":false,"server_page_length":10,"row_limit":50000,"percent_metric_calculation":"row_limit","table_timestamp_format":"smart_date","include_search":true,"allow_rearrange_columns":true,"allow_render_html":true,"column_config":{"discount":{"horizontalAlign":"right","truncateLongCells":true},"line_id":{"showCellBars":false},"order_id":{"showCellBars":false},"order_tax_amount":{"d3NumberFormat":",.2f","d3SmallNumberFormat":",.2f","horizontalAlign":"right","truncateLongCells":true},"order_total_price_paid":{"currencyFormat":{},"d3NumberFormat":",.2f","d3SmallNumberFormat":",.2f","horizontalAlign":"right","showCellBars":false},"order_total_price_paid_plus_tax":{"currencyFormat":{},"d3NumberFormat":",.2f","d3SmallNumberFormat":",.2f","showCellBars":false},"receipt_payment_amount":{"d3NumberFormat":",.2f","d3SmallNumberFormat":",.2f","horizontalAlign":"right","truncateLongCells":false},"unit_price":{"currencyFormat":{},"d3NumberFormat":",.2f","d3SmallNumberFormat":",.2f","horizontalAlign":"right","showCellBars":false}},"show_cell_bars":false,"color_pn":false,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[33],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: c0ce9f7b-a8e8-49d3-909b-9c44718fae8a
version: 1.0.0
dataset_uuid: 02e97623-3edd-4d3a-acbe-119e889a043a
