slice_name: Organization Administration Details
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  viz_type: table
  query_mode: raw
  groupby: []
  temporal_columns_lookup:
    activity_date: true
  metrics: []
  all_columns:
  - activity_date
  - courserun_readable_id
  - user_email
  - certificate_count
  - chatbot_used_count
  - enrolled_count
  - videos_watched
  - problems_count
  - active_count
  - organization_key
  - organization_name
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_mo7htfhi6rl_vl2v502xnz
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: activity_date
  - clause: WHERE
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_iqjdjvd1dv_0qu415ddiasa
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: organization_name
  order_by_cols: []
  row_limit: 10000
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    SUM(active_count):
      showCellBars: false
    SUM(certificate_count):
      showCellBars: false
    SUM(chatbot_used_count):
      showCellBars: false
    SUM(enrolled_count):
      showCellBars: false
    SUM(problems_count):
      showCellBars: false
    SUM(videos_watched):
      showCellBars: false
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
query_context: '{"datasource":{"id":152,"type":"table"},"force":false,"queries":[{"filters":[{"col":"activity_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"organization_name","op":"IS NOT NULL"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["activity_date","courserun_readable_id","user_email","certificate_count","chatbot_used_count","enrolled_count","videos_watched","problems_count","active_count","organization_key","organization_name"],"orderby":[],"annotation_layers":[],"row_limit":10000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"152__table","viz_type":"table","slice_id":163,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{"activity_date":true},"metrics":[],"all_columns":["activity_date","courserun_readable_id","user_email","certificate_count","chatbot_used_count","enrolled_count","videos_watched","problems_count","active_count","organization_key","organization_name"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_mo7htfhi6rl_vl2v502xnz","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"activity_date"},{"clause":"WHERE","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_iqjdjvd1dv_0qu415ddiasa","isExtra":false,"isNew":false,"operator":"IS
  NOT NULL","operatorId":"IS_NOT_NULL","sqlExpression":null,"subject":"organization_name"}],"order_by_cols":[],"row_limit":10000,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"SUM(active_count)":{"showCellBars":false},"SUM(certificate_count)":{"showCellBars":false},"SUM(chatbot_used_count)":{"showCellBars":false},"SUM(enrolled_count)":{"showCellBars":false},"SUM(problems_count)":{"showCellBars":false},"SUM(videos_watched)":{"showCellBars":false}},"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 25373a70-93aa-4685-88c7-afdc137cd660
version: 1.0.0
dataset_uuid: 4a71d2a9-c1b2-44e7-8c8d-a4a336779ab8 # organization_administration_report
