cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 4a71d2a9-c1b2-44e7-8c8d-a4a336779ab8  # organization_administration_report
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: certificate_created_date
  all_columns:
  - platform
  - organization
  - course_title
  - courserun_readable_id
  - user_email
  - activity_date
  - certificate_count
  - chatbot_used_count
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    activity_date: true
  time_grain_sqla: P1D
  viz_type: table
slice_name: Organization Administration Detail Report
uuid: caf22ae5-3cde-427d-8627-cd55c5febd87
version: 1.0.0
viz_type: table
