cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f221af29-5df4-4025-8355-401041f94835  # marts__combined_course_engagements
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    '%_of_Learners_Participated_In_Discussion':
      d3SmallNumberFormat: ',.1%'
    '%_of_Learners_That_Played_A_Video':
      d3NumberFormat: ',.1%'
    '%_of_Learners_That_Submitted_Problem':
      d3SmallNumberFormat: ',.1%'
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards: []
  extra_form_data: {}
  groupby:
  - courserun_readable_id
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_That_Played_A_Video'
    optionName: metric_l5c334byisa_p7rmx2wh92
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_video_played> 0 THEN user_username
      ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_That_Submitted_Problem'
    optionName: metric_ylcblnqaund_cnq3layng0u
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_problem_submitted> 0 THEN user_username
      ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_Participated_In_Discussion'
    optionName: metric_bv6eq24ga6m_3ew9eu11jld
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_discussion_participated> 0
      THEN user_username ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    courseactivity_date: true
  viz_type: table
slice_name: Percent Content Engagement
uuid: 822d24da-190a-49ea-9253-8a26637a89c8
version: 1.0.0
viz_type: table
