cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: edf21d6a-1f41-4812-a1aa-3fcbc8358466  # marts__combined_total_course_engagements
description: null
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    Avg_Percent_Discussions_Engaged_In:
      d3NumberFormat: ',.1%'
    Avg_Percent_Problems_Submitted:
      d3NumberFormat: ',.1%'
    Avg_Percent_Videos_Watched:
      d3NumberFormat: ',.1%'
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards: []
  extra_form_data: {}
  groupby:
  - courserun_readable_id
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_Percent_Videos_Watched
    optionName: metric_3fzcijigbwq_2t7y5h574xm
    sqlExpression: "AVG(CASE WHEN total_courserun_videos> 0 \nTHEN cast(videos_user_watched\
      \ AS decimal(10,2))/cast(total_courserun_videos AS decimal(10,2)) END)"
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_Percent_Problems_Submitted
    optionName: metric_q1zxtsv7f8o_4tezx4gzhbi
    sqlExpression: "AVG(CASE WHEN total_courserun_problems> 0 \nTHEN cast(problems_user_submitted\
      \ AS decimal(10,2))/cast(total_courserun_problems AS decimal(10,2)) END)"
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_Percent_Discussions_Engaged_In
    optionName: metric_qg66l351ox_kqf9cnj5vk
    sqlExpression: "AVG(CASE WHEN total_courserun_discussions> 0 \nTHEN cast(user_discussion_count\
      \ AS decimal(10,2))/cast(total_courserun_discussions AS decimal(10,2)) END)"
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: Percent Engagement Out of Total Engagement Opportunities
uuid: 3bc78cde-60af-405c-9d7d-13e61558c228
version: 1.0.0
viz_type: table
