slice_name: Problem Engagement Test Report
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  color_pn: true
  column_config:
    '%_Problems_Attempted':
      d3NumberFormat: ',.1%'
    '%_Problems_Correct':
      d3NumberFormat: ',.1%'
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards: []
  extra_form_data: {}
  groupby:
  - section_title
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_Problems_Attempted'
    optionName: metric_224mez8063pi_ew9xvc2r8v7
    sqlExpression: sum(cast(attepted_true_cnt as decimal(30,10)))/count(*)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_Problems_Correct'
    optionName: metric_nvhhsl8lrm_khgrazj7kpo
    sqlExpression: sum(cast(correct_true_cnt as decimal(30,10)))/count(*)
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 93
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: c05f9d50-bb41-4058-9f35-1ec46ec907c9
version: 1.0.0
dataset_uuid: 37bb25c7-421f-432a-bc42-5cc10a129746
