cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 4490876f-d440-4df8-8e42-a467bac0821f  # engagement_problem_completion_raw
description: null
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    Avg_%_problems_attempted:
      d3NumberFormat: ',.1%'
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby:
  - courserun_readable_id
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_%_problems_attempted
    optionName: metric_v0x9x3vkxs_lyd8fkz8ah
    sqlExpression: AVG(percent_problems_attempted)
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
uuid: 1e30a45b-d97d-4f44-ac2c-1d9de9e05bc1
version: 1.0.0
