cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0983d23f-8182-482a-9f0f-b32d69984efc  # marts__combined_program_enrollment_detail
description: null
params:
  adhoc_filters: []
  all_columns:
  - platform_name
  - program_type
  - program_name
  - program_track
  - program_readable_id
  - user_id
  - user_full_name
  - user_email
  - programenrollment_enrollment_status
  - programenrollment_is_active
  - programenrollment_created_on
  - user_has_completed_program
  - programcertificate_created_on
  - programcertificate_url
  - programcertificate_is_revoked
  - program_is_live
  - program_title
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    user_id:
      showCellBars: false
  conditional_formatting: []
  dashboards:
  - 34
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Program Enrollment and Certificate
uuid: b100bef9-c9f8-46f5-b6ef-20b2badecef4
version: 1.0.0
viz_type: table
