cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: cc496da8-03f6-43ea-9b6c-900ba695e4b6  # Program_Enrollment_with_user
description: null
params:
  adhoc_filters: []
  all_columns:
  - platform_name
  - program_type
  - program_name
  - program_track
  - program_readable_id
  - user_id
  - user_full_name
  - user_email
  - programenrollment_enrollment_status
  - programenrollment_is_active
  - programenrollment_created_on
  - expressionType: SQL
    label: user_has_completed_program
    sqlExpression: CASE WHEN programcertificate_created_on is not null then true else
      user_has_completed_program end
  - programcertificate_created_on
  - programcertificate_url
  - programcertificate_is_revoked
  - program_is_live
  - program_title
  - user_industry
  - user_company
  - user_job_title
  - user_highest_education
  - program_complete_days
  - courses_taken_in_program
  - capstone_ind
  - user_birth_year
  - user_gender
  - user_address_country
  - user_street_address
  - user_address_city
  - user_address_state_or_territory
  - user_address_postal_code
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    courses_taken_in_program:
      showCellBars: false
    program_complete_days:
      showCellBars: false
    user_id:
      showCellBars: false
  comparison_color_scheme: Green
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
slice_name: Program Enrollment and Certificate
uuid: d9047161-f8d8-4af2-adb0-283c74b639f2
version: 1.0.0
viz_type: table
