cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 0d77ec2b-8489-47f8-b0c3-3abde0b1b8f3  # program_summary_report
description: null
params:
  adhoc_filters: []
  all_columns:
  - program_name
  - total_enrollments
  - unique_users
  - unique_countries
  - verified_enrollments
  - unique_verified_users
  - course_certificates
  - unique_course_certificate_earners
  - program_certificates
  allow_render_html: false
  annotation_layers: []
  color_pn: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 34
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: false
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: Program Summary
uuid: 8350fe92-c02c-4e98-92ed-adabae3fb582
version: 1.0.0
viz_type: table
