cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: f3e517dd-4012-441e-8dfe-edaef1318000  # combined_enrollments_with_gender_and_date
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  extra_form_data: {}
  header_font_size: 0.4
  metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Record Count
    optionName: metric_odjay9cgkon_z1khg8fnb8o
    sqlExpression: COUNT(*)
  subheader_font_size: 0.15
  time_format: smart_date
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
slice_name: Record Count
uuid: 1e441a91-5d1a-4f4f-9bf8-90fcc9d12988
version: 1.0.0
viz_type: big_number_total
