cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: ca346322-251e-455b-a2cc-b11976e69ce5  # student_risk_probability_report
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: created_timestamp
  all_columns:
  - platform
  - openedx_user_id
  - email
  - courserun_readable_id
  - courserungrade_grade
  - datasourceWarning: false
    expressionType: SQL
    label: suspiciousness_probability
    sqlExpression: risk_probability
  allow_render_html: true
  annotation_layers: []
  color_pn: false
  column_config:
    openedx_user_id:
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  percent_metrics: []
  query_mode: raw
  row_limit: 500000
  show_cell_bars: false
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    created_timestamp: true
  viz_type: table
slice_name: Student Level Course Grades
uuid: 1a78ac33-5081-4fb7-9593-89b1aed6daad
version: 1.0.0
viz_type: table
