slice_name: Tutorbot with filter
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - course-v1:MITxT+7.28.1x+2T2025
    - course-v1:MITxT+7.28.1x+1T2025
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_g6mu0yslf5h_vhz9j0j2j0m
    isExtra: false
    isNew: false
    operator: NOT IN
    operatorId: NOT_IN
    sqlExpression: null
    subject: courserun_readable_id
  all_columns:
  - tutorbotoutput_id
  - chatsession_thread_id
  - tutorbot_chat_json
  - chatsession_agent
  - chatsession_title
  - courserun_readable_id
  - edx_module_id
  - user_id
  - user_email
  - user_full_name
  - user_username
  - user_global_id
  - chatsession_created_on
  - chatsession_updated_on
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards: []
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 116
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: bc2f4ec2-0532-4a55-8482-e12ecae7e7de
version: 1.0.0
dataset_uuid: 4fe652f8-e672-4e71-89da-fb964985847b
