slice_name: Video Engagement By Section and Subsection
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_10jjuuuzm15p_kc7p163o0mf
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: section_title
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    Estimated_Time_Played(seconds):
      showCellBars: false
    Percentage_Watched:
      d3NumberFormat: ',.1%'
    video_duration(seconds):
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 45
  extra_form_data: {}
  groupby:
  - section_title
  - subsection_title
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Percentage_Watched
    optionName: metric_dumltzcco9n_29nb76o699x
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration as decimal(30,10))), 0)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: video_duration(seconds)
    optionName: metric_juj3y7jx6lk_6zind68s0zo
    sqlExpression: SUM(cast(video_duration as decimal(30,10)))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Estimated_Time_Played(seconds)
    optionName: metric_o9t2udcpzu_b65p8iu5j9p
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)
  order_by_cols: []
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  show_cell_bars: true
  slice_id: 98
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
query_context: null
cache_timeout: null
uuid: 738b9337-2477-4f49-95e6-4201a90c6f28
version: 1.0.0
dataset_uuid: 4752cd11-a13e-4a8e-be31-4d9227b07ca2
