cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 42f063d3-3c06-4834-b993-777fdbc6dea7  # marts__combined_video_engagements_w_video_counts
description: null
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  contributionMode: null
  extra_form_data: {}
  form_data_bak:
    adhoc_filters: []
    bottom_margin: auto
    color_scheme: supersetColors
    columns: []
    dashboards:
    - 24
    datasource: 43__table
    extra_form_data: {}
    groupby:
    - section_title
    metrics:
    - aggregate: null
      column: null
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed At Least One Video
      optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
      sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
        else null end))
    - aggregate: null
      column: null
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed All Videos
      optionName: metric_547rhhgzkqw_1i0h85x10p7
      sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
        then user_email else null end))
    order_desc: false
    rich_tooltip: true
    row_limit: 10000
    show_legend: true
    slice_id: 44
    timeseries_limit_metric:
      aggregate: MIN
      column:
        advanced_data_type: null
        certification_details: null
        certified_by: null
        column_name: max_coursestructure_block_index
        description: null
        expression: null
        filterable: true
        groupby: true
        id: 661
        is_certified: false
        is_dttm: false
        python_date_format: null
        type: BIGINT
        type_generic: 0
        verbose_name: null
        warning_markdown: null
      datasourceWarning: false
      expressionType: SIMPLE
      hasCustomLabel: false
      label: MIN(max_coursestructure_block_index)
      optionName: metric_l5fmf7i5xb_rbdvkyjo29h
      sqlExpression: null
    viz_type: dist_bar
    x_ticks_layout: auto
    y_axis_bounds:
    - null
    - null
    y_axis_format: SMART_NUMBER
  groupby: []
  markerEnabled: false
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed At Least One Video
    optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
    sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed All Videos
    optionName: metric_547rhhgzkqw_1i0h85x10p7
    sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
      then user_email else null end))
  order_desc: false
  queries_bak:
  - annotation_layers: []
    applied_time_extras: {}
    columns:
    - section_title
    custom_form_data: {}
    custom_params: {}
    extras:
      having: ''
      where: ''
    filters: []
    metrics:
    - aggregate: null
      column: null
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed At Least One Video
      optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
      sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
        else null end))
    - aggregate: null
      column: null
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed All Videos
      optionName: metric_547rhhgzkqw_1i0h85x10p7
      sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
        then user_email else null end))
    order_desc: false
    row_limit: 10000
    series_limit: 0
    series_limit_metric:
      aggregate: MIN
      column:
        advanced_data_type: null
        certification_details: null
        certified_by: null
        column_name: max_coursestructure_block_index
        description: null
        expression: null
        filterable: true
        groupby: true
        id: 661
        is_certified: false
        is_dttm: false
        python_date_format: null
        type: BIGINT
        type_generic: 0
        verbose_name: null
        warning_markdown: null
      datasourceWarning: false
      expressionType: SIMPLE
      hasCustomLabel: false
      label: MIN(max_coursestructure_block_index)
      optionName: metric_l5fmf7i5xb_rbdvkyjo29h
      sqlExpression: null
    url_params: {}
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  stack: null
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: max_coursestructure_block_index
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 661
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(max_coursestructure_block_index)
    optionName: metric_l5fmf7i5xb_rbdvkyjo29h
    sqlExpression: null
  truncateYAxis: true
  viz_type: echarts_timeseries_bar
  xAxisLabelRotation: 45
  x_axis: section_title
  x_axis_title_margin: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  zoomable: false
slice_name: Video Engagement per Section
uuid: f9c49065-6eb1-4c47-ab2b-a03654cdcbc4
version: 1.0.0
viz_type: echarts_timeseries_bar
