slice_name: Video Engagement By Section
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_h2ui7krcd97_90orw6j53ew
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: section_title
  all_columns:
  - courserun_readable_id
  - section_title
  - datasourceWarning: false
    expressionType: SQL
    label: Percentage_Watched
    sqlExpression: sum(estimated_time_played)/sum(video_duration)
  - datasourceWarning: false
    expressionType: SQL
    label: estimated_time_played
    sqlExpression: sum(estimated_time_played)
  - datasourceWarning: false
    expressionType: SQL
    label: video_duration
    sqlExpression: sum(video_duration)
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  column_config:
    Percent_watched:
      d3NumberFormat: ',.1%'
    estimated_time_played(seconds):
      showCellBars: false
    video_duration(seconds):
      showCellBars: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 45
  extra_form_data: {}
  groupby:
  - section_title
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Percent_watched
    optionName: metric_6l0bn69a8cc_jhnt19d39ol
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration as decimal(30,10))), 0)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: video_duration(seconds)
    optionName: metric_9ikc05p2ule_uk6978spa
    sqlExpression: SUM(cast(video_duration as decimal(30,10)))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: estimated_time_played(seconds)
    optionName: metric_ph8fgwcoutr_mija3tw2q2d
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)
  order_by_cols: []
  order_desc: false
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  show_cell_bars: true
  slice_id: 85
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  timeseries_limit_metric: null
  viz_type: table
query_context: null
cache_timeout: null
uuid: f37fc707-aeb4-4731-b0d5-634b47a57eae
version: 1.0.0
dataset_uuid: 4752cd11-a13e-4a8e-be31-4d9227b07ca2
