cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: dc5b25f5-cf3a-41b4-9b15-4b58532da463  # marts__mitxpro_ecommerce_productlist
description: null
params:
  adhoc_filters: []
  all_columns:
  - productid
  - product_name
  - product_readable_id
  - product_type
  - list_price
  - product_description
  - start_date
  - end_date
  - enrollment_start
  - enrollment_end
  - link
  annotation_layers: []
  color_pn: true
  comparison_type: values
  extra_form_data: {}
  groupby:
  - productid
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 50000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  time_grain_sqla: P1D
  viz_type: table
slice_name: xPRO Product List - Standard Products Only
uuid: 244158fe-79de-4ad8-bc53-f82ef3f32ffa
version: 1.0.0
viz_type: table
