cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 75791fe7-a03c-4cbe-a3f5-04dd48c58c2e
description: null
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: ticket_due_at
  align_pn: false
  all_columns:
  - ticket_id
  - ticket_created_at
  - ticket_requester
  - ticket_description
  - brand_name
  - group_name
  allow_rearrange_columns: false
  allow_render_html: true
  color_pn: true
  comparison_color_enabled: false
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  extra_form_data: {}
  groupby: []
  include_search: true
  matrixify_all_sort_by_columns: a_to_z
  matrixify_all_sort_by_rows: a_to_z
  matrixify_cell_title_template: ''
  matrixify_charts_per_row: 3
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_selection_mode_rows: members
  matrixify_enable: false
  matrixify_fit_columns_dynamically: true
  matrixify_mode_columns: disabled
  matrixify_mode_rows: disabled
  matrixify_row_height: 300
  matrixify_show_column_headers: true
  matrixify_show_row_labels: true
  matrixify_topn_order_columns: true
  matrixify_topn_order_rows: true
  matrixify_topn_value_columns: 10
  matrixify_topn_value_rows: 10
  order_by_cols:
  - '["ticket_created_at", false]'
  percent_metrics: []
  query_mode: raw
  row_limit: 100000
  server_pagination: false
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    ticket_due_at: true
  viz_type: table
slice_name: Zendesk Tickets
uuid: a9455790-a0bc-4ab2-94fc-e656e0889a8f
version: 1.0.0
viz_type: table
