---
# Build context is set to repository root to access packages/ol-orchestrate-lib
directory: ../..
# The Dockerfile is located in the data_platform directory
dockerfile: dg_projects/data_platform/Dockerfile
registry: mitodl/dagster-data_platform
