{{ config(
    materialized='table'
) }}

-- The analysis fact: one row per conversation, carrying lifecycle attributes and every
-- model-generated attribute. A complaint usually emerges over several turns, so the
-- conversation -- not the turn -- is the unit that gets summarized, embedded, scored and
-- clustered. Fully rebuildable without touching tfact_feedback.
with conversation as (
    select * from {{ ref('int__feedback__conversation') }}
)

, feedback as (
    select * from {{ ref('tfact_feedback') }}
)

, ticket as (
    select * from {{ ref('int__zendesk__ticket') }}
)

, ticket_comment as (
    select * from {{ ref('int__zendesk__ticket_comment') }}
)

, sentiment as (
    select
        sentiment_pk
        , sentiment_slug
    from {{ ref('dim_sentiment') }}
)

, turn_aggregates as (
    select
        conversation_id
        , feedback_source_fk
        , min(occurred_date_fk) as opened_date_fk
        , max(occurred_date_fk) as last_turn_date_fk
        , min(user_fk) as opened_by_user_fk
    from feedback
    group by conversation_id, feedback_source_fk
)

-- Counted over the ticket's FULL comment history, not the kept turns: the requester
-- filter leaves a single author by construction, so aggregating kept turns would always
-- return 1 rather than the number of people in the conversation.
, participants as (
    select
        cast(ticket_id as varchar) as conversation_ref
        , count(distinct comment_author_user_id) as participant_count
    from ticket_comment
    group by ticket_id
)

select
    {{ dbt_utils.generate_surrogate_key(['conversation.source_slug', 'conversation.conversation_ref']) }}
        as feedback_conversation_pk
    , conversation.conversation_ref as conversation_id
    , turn_aggregates.feedback_source_fk
    , turn_aggregates.opened_by_user_fk
    , turn_aggregates.opened_date_fk
    , turn_aggregates.last_turn_date_fk
    , conversation.turn_count
    , participants.participant_count
    , conversation.conversation_text_chars
    , ticket.ticket_status as final_status
    , ticket.ticket_satisfaction_rating_score as explicit_rating
    -- Tier 1 of the sentiment ladder: the explicit rating, at last a grain-matched
    -- signal. 'offered' and null are an ABSENCE of signal, not a neutral one -- they
    -- stay null so the model tier can find and fill exactly those rows.
    , sentiment.sentiment_pk as sentiment_fk
    , case
        when ticket.ticket_satisfaction_rating_score in ('good', 'bad') then 'explicit_rating'
    end as sentiment_source
    -- Generated by the ML asset (spec 7). All nullable; this table is queryable and
    -- useful before any of them are populated.
    , cast(null as varchar) as conversation_summary
    , cast(null as varchar) as summary_model_version
    , cast(null as varchar) as summarized_at
    , cast(null as array(double)) as embedding_vector
    , cast(null as integer) as embedding_dim
    , cast(null as varchar) as embedding_model_version
    , cast(null as varchar) as embedding_input
    , cast(null as varchar) as embedded_at
    , cast(null as varchar) as category_fk
    , cast(null as varchar) as cluster_run_id
    , cast(null as integer) as cluster_id
    , cast(null as double) as cluster_probability
    , {{ cast_timestamp_to_iso8601('current_timestamp') }} as conversation_ingested_at
from conversation
inner join turn_aggregates
    on conversation.conversation_ref = turn_aggregates.conversation_id
-- inner join, not left: a ticket whose only public comments are agent-authored
-- contributes no turns, and a conversation row with no turns would fail the
-- bidirectional relationships test against tfact_feedback
inner join ticket
    on conversation.conversation_ref = cast(ticket.ticket_id as varchar)
left join participants
    on conversation.conversation_ref = participants.conversation_ref
left join sentiment
    on sentiment.sentiment_slug = case ticket.ticket_satisfaction_rating_score
        when 'good' then 'positive'
        when 'bad' then 'negative'
    end
