{{ config(
    materialized='table'
) }}

-- The analysis fact: one row per conversation. A complaint usually emerges over several
-- turns, so the conversation is the unit that gets summarized, embedded, scored and
-- clustered. Fully rebuildable without touching tfact_feedback.
with conversation as (
    select * from {{ ref('int__feedback__conversation') }}
)

, feedback as (
    select * from {{ ref('tfact_feedback') }}
)

, ticket as (
    select * from {{ ref('int__zendesk__ticket') }}
)

, ticket_comment as (
    select * from {{ ref('int__zendesk__ticket_comment') }}
)

, sentiment as (
    select
        sentiment_pk
        , sentiment_slug
    from {{ ref('dim_sentiment') }}
)

, turn_aggregates as (
    select
        conversation_id
        , feedback_source_fk
        , min(occurred_date_fk) as opened_date_fk
        , max(occurred_date_fk) as last_turn_date_fk
        -- the opening turn's author, not min() over the group: an arbitrary pick
        -- disagrees wherever one turn resolves an identity and another does not
        , max(case when is_conversation_opening then user_fk end) as opened_by_user_fk
    from feedback
    group by conversation_id, feedback_source_fk
)

-- Counted over the ticket's full comment history: the requester filter leaves a single
-- author by construction, so aggregating the kept turns would always return 1.
, participants as (
    select
        cast(ticket_id as varchar) as conversation_ref
        , count(distinct comment_author_user_id) as participant_count
    from ticket_comment
    group by ticket_id
)

, conversation_tag as (
    select distinct
        feedback.feedback_source_fk
        , feedback.conversation_id
        , feedback_tag.tag_slug
    from feedback
    inner join {{ ref('bridge_feedback_tag') }} as bridge
        on feedback.feedback_pk = bridge.feedback_pk
    inner join {{ ref('dim_feedback_tag') }} as feedback_tag
        on bridge.feedback_tag_pk = feedback_tag.feedback_tag_pk
)

, tag_frequency as (
    select
        tag_slug
        , count(*) as conversation_count
    from conversation_tag
    group by tag_slug
)

-- Tags are a ticket attribute, so every tag on a conversation has the same
-- within-conversation count. Corpus frequency is the only ordering that discriminates a
-- dominant tag; tag_slug breaks the remaining ties so the pick is deterministic.
, ranked_tag as (
    select
        conversation_tag.feedback_source_fk
        , conversation_tag.conversation_id
        , conversation_tag.tag_slug
        , row_number() over (
            partition by conversation_tag.feedback_source_fk, conversation_tag.conversation_id
            order by tag_frequency.conversation_count desc, conversation_tag.tag_slug
        ) as tag_rank
    from conversation_tag
    inner join tag_frequency on conversation_tag.tag_slug = tag_frequency.tag_slug
)

, dominant_tag as (
    select
        feedback_source_fk
        , conversation_id
        , tag_slug
    from ranked_tag
    where tag_rank = 1
)

, feedback_category as (
    select
        feedback_category_pk
        , category_slug
    from {{ ref('dim_feedback_category') }}
)

select
    {{ dbt_utils.generate_surrogate_key(['conversation.source_slug', 'conversation.conversation_ref']) }}
        as feedback_conversation_pk
    , conversation.conversation_ref as conversation_id
    , turn_aggregates.feedback_source_fk
    , turn_aggregates.opened_by_user_fk
    , turn_aggregates.opened_date_fk
    , turn_aggregates.last_turn_date_fk
    , conversation.turn_count
    , participants.participant_count
    , conversation.conversation_text_chars
    , ticket.ticket_status as final_status
    , ticket.ticket_satisfaction_rating_score as explicit_rating
    -- Tier 1 of the sentiment ladder. Only 'good' and 'bad' are verdicts; 'unoffered'
    -- (no survey sent) and 'offered' (sent, unanswered) are kinds of absence rather than
    -- neutral ratings, so both stay null for the model tier to fill.
    , sentiment.sentiment_pk as sentiment_fk
    , case
        when ticket.ticket_satisfaction_rating_score in ('good', 'bad') then 'explicit_rating'
    end as sentiment_source
    -- Generated by the ML asset. All nullable; the table is useful before they land.
    , cast(null as varchar) as conversation_summary
    , cast(null as varchar) as summary_model_version
    , cast(null as varchar) as summarized_at
    , cast(null as array(double)) as embedding_vector
    , cast(null as integer) as embedding_dim
    , cast(null as varchar) as embedding_model_version
    , cast(null as varchar) as embedding_input
    , cast(null as varchar) as embedded_at
    -- The tag-seed assignment; the ML asset reassigns from clusters later. A
    -- conversation with no tags stays null, the queryable unassigned state.
    , feedback_category.feedback_category_pk as category_fk
    , cast(null as varchar) as cluster_run_id
    , cast(null as integer) as cluster_id
    , cast(null as double) as cluster_probability
    , {{ cast_timestamp_to_iso8601('current_timestamp') }} as conversation_ingested_at
from conversation
inner join turn_aggregates
    on conversation.conversation_ref = turn_aggregates.conversation_id
-- inner join, not left: a ticket whose only public comments are agent-authored
-- contributes no turns, and a conversation row with no turns fails the bidirectional
-- turn coverage tests
inner join ticket
    on conversation.conversation_ref = cast(ticket.ticket_id as varchar)
left join participants
    on conversation.conversation_ref = participants.conversation_ref
left join dominant_tag
    on conversation.conversation_ref = dominant_tag.conversation_id
    and turn_aggregates.feedback_source_fk = dominant_tag.feedback_source_fk
left join feedback_category
    on dominant_tag.tag_slug = feedback_category.category_slug
left join sentiment
    on sentiment.sentiment_slug = case ticket.ticket_satisfaction_rating_score
        when 'good' then 'positive'
        when 'bad' then 'negative'
    end
