"""EdX.org S3 CSV/TSV data ingestion via dlt.

Loads TSV files from S3 that are generated by the ``edxorg_archive`` asset.
These files contain database-table exports from edX.org courses.

S3 structure::

    s3://.../edxorg-raw-data/edxorg/raw_data/db_table/{table}/{system}/{course}/{hash}.tsv

The set of tables to load is supplied by the caller (the ``data_loading``
Dagster wrapper passes ``EDXORG_DB_TABLES`` from ``ol_orchestrate``); this source
stays pure dlt and owns no Dagster/orchestration dependencies.

Run standalone:
    DLT_PROFILE=dev python -m ol_dlt.sources.edxorg_s3
"""

import logging
import shutil
import tempfile
from collections.abc import Generator, Iterable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import dlt
import s3fs
from dlt.sources import incremental
from dlt.sources.filesystem import FileItemDict
from dlt.sources.filesystem.helpers import fetch_arrow

from ol_dlt import config
from ol_dlt.file_metadata import FILE_METADATA_COLUMNS, add_file_metadata

logger = logging.getLogger(__name__)

# Source bucket (the edxorg archive landing zone). This is always the production
# landing zone regardless of the active profile — it is where TSVs are read FROM,
# not where data is written TO.
_EDXORG_LANDING_BUCKET = (
    "s3://ol-data-lake-landing-zone-production/edxorg-raw-data/edxorg/raw_data/"
)

_EDXORG_PRIMARY_KEY = ["row_hash", "extracted_course_key"]

# Options handed to DuckDB's CSV reader for every edxorg TSV.
_CSV_READER_OPTIONS: dict[str, Any] = {
    "delimiter": "\t",  # TSV files use tabs
    "ignore_errors": True,
    # These are dumps of user-entered free text (auth_userprofile.bio, .goals,
    # .mailing_address and friends), so a field occasionally carries a bare CR
    # or a CRLF while the rest of the file is LF-terminated. DuckDB's strict
    # mode treats mixed newlines as a dialect violation, and the dialect sniffer
    # runs BEFORE ignore_errors can suppress anything -- so one stray CR kills
    # the entire resource with "It was not possible to automatically detect the
    # CSV parsing dialect" instead of skipping the one bad row. Relaxing strict
    # mode lets the sniffer settle on a dialect and routes the malformed rows to
    # ignore_errors, where they belong. Clean LF and clean CRLF files parse
    # identically either way.
    #
    # Deliberately NOT setting null_padding: on a row with more fields than the
    # header it would materialise synthetic `columnN` columns, which vary per
    # file and would churn the destination schema.
    "strict_mode": False,
    # Pin the quote/escape dialect instead of letting the sniffer guess it.
    # The upstream edxorg_archive asset writes these files with polars'
    # quote_style="necessary", which uses RFC-4180 doubling -- an embedded `"`
    # is written as `""` inside a quoted field. Left to its own devices the
    # sniffer picks a quote/escape pair that does NOT undouble it, so
    # `he said "hi"` silently reads back as `he said ""hi""`. Setting escapechar
    # to the quote character makes the undoubling explicit.
    #
    # The older, entirely unquoted files still sitting in the landing zone parse
    # identically under these pins, with one exception: a value that happens to
    # begin with `"` opens a quoted field that never closes, swallowing the tabs
    # and newlines after it until the sniffer gives up. read_edxorg_tsv falls
    # back to reading such a file unquoted (see _read_unquoted_tsv).
    "quotechar": '"',
    "escapechar": '"',
    # Force all columns to VARCHAR to prevent pyarrow schema mismatches across
    # files (e.g. TIMESTAMP vs VARCHAR for a column that is empty in some
    # files). dbt casts downstream.
    "all_varchar": True,
}

# Quoting off, for the legacy unquoted dumps. Their quotes are literal text
# (auth_userprofile.meta's JSON, for one), so no quote character is what the
# data actually means.
_UNQUOTED_READER_OVERRIDES: dict[str, Any] = {"quotechar": "", "escapechar": ""}

_DOWNLOAD_CHUNK_BYTES = 8 * 1024 * 1024

# How much source TSV one dlt load may cover. dlt's Iceberg writer materializes
# a whole load as one Arrow table (`write_iceberg_table` receives
# `arrow_dataset.to_table()`; only the Delta path streams), so the load step's
# peak memory tracks this number: measured 2.70 GB for a 1.1 GB batch and
# 6.34 GB for 3.34 GB, about 0.9 GB + 1.6x the batch. A full 4 GiB batch is
# therefore ~7.8 GB, and the batch holding the 14.5 GB export -- a file larger
# than the budget forms a batch of its own -- is ~24 GB. See the job's memory
# limit and concurrency in data_loading's ingestion sensor.
#
# The backlog is walked one budget at a time rather than in a single load:
# 11.1 TB of courseware_studentmodule does not fit in any pod, and a kill
# costs one batch instead of the whole run.
_DEFAULT_BUDGET_BYTES = 4 * 1024**3


class EdxorgTSVUnreadableError(Exception):
    """DuckDB could not read one edxorg TSV, named in the message."""


@contextmanager
def _local_copy(item: FileItemDict) -> Iterator[Path]:
    """Download ``item`` to a temporary file so DuckDB can read it by path.

    Handing ``from_csv_auto`` a Python file object makes DuckDB call
    ``obj.read()`` on the whole thing and keep the bytes in its in-memory
    object store (``duckdb/filesystem.py``, ``ModifiedMemoryFileSystem.add_file``)
    before parsing a single row. Reading a 1.1 GB courseware_studentmodule
    export from the landing zone that way peaked at 3.9 GB RSS; from a local
    copy, 0.63 GB, with the same 2,499,922 rows. The largest export is 14.5 GB,
    well past the ingest pod's 32Gi limit at that ratio.

    The copy goes through ``item.open()`` -- the source's s3fs filesystem, whose
    IRSA credentials refresh -- rather than DuckDB's httpfs, whose
    ``credential_chain`` secret snapshots the credentials once and would expire
    partway through a long run.
    """
    with tempfile.TemporaryDirectory(prefix="edxorg_tsv_") as tmp_dir:
        path = Path(tmp_dir, item["file_name"])
        with item.open() as source, path.open("wb") as destination:
            shutil.copyfileobj(source, destination, _DOWNLOAD_CHUNK_BYTES)
        yield path


def _read_tsv(
    path: Path, chunk_size: int, duckdb_kwargs: dict[str, Any]
) -> Iterator[Any]:
    """Stream ``path`` as Arrow batches instead of materializing the whole file.

    CSV dialect sniffing happens inside ``from_csv_auto`` itself, before this
    function's first ``yield`` -- confirmed by triggering a sniff failure
    against a real DuckDB relation, which raised at relation construction with
    zero batches fetched. That only makes the FIRST ``next()`` call safe to
    retry, though: a ``duckdb.Error`` raised while consuming a LATER batch
    (mid-scan corruption, an I/O hiccup) is a real possibility this function
    does not rule out, and by then some rows have already left this generator.
    Callers must not blanket-retry on any ``duckdb.Error`` the way they safely
    could when this returned a fully-materialized list -- see the priming
    pattern in ``read_edxorg_tsv``, which only allows the pinned-vs-unquoted
    fallback before the first batch is yielded and surfaces anything after
    that as a hard failure instead.

    Streaming (rather than buffer-then-return) still matters: one edxorg
    export can be multiple GB, and the previous ``list(fetch_arrow(...))``
    held an entire file's decoded rows in memory at once.
    """
    import duckdb  # noqa: PLC0415

    relation = duckdb.from_csv_auto(str(path), **duckdb_kwargs)
    yield from fetch_arrow(relation, chunk_size)


def _data_line_count(path: Path) -> int:
    """Count the non-blank lines after the header, streaming line by line.

    Blank lines are excluded because DuckDB skips them: counting raw newlines
    would reject a file with a trailing or stray blank line even though every
    record in it was read.
    """
    with path.open("rb") as file_handle:
        return sum(1 for line in file_handle if line.rstrip(b"\r\n")) - 1


def _read_unquoted_tsv(
    path: Path, file_url: str, chunk_size: int, duckdb_kwargs: dict[str, Any]
) -> list[Any] | None:
    """Read ``path`` with quoting off, or return None if that loses any rows.

    ``file_url`` is only for the log lines: the local copy's name is a content
    hash that maps to nothing anyone can open.

    Only right for the legacy dumps, where every line is exactly one record, so
    that is checked rather than assumed. ``ignore_errors`` drops rows it cannot
    parse without saying so, and a fallback that quietly loads part of a file is
    worse than the loud failure it replaces: the production file behind
    DAGSTER-30, read with explicit columns and quoting on, loaded 1,345 of its
    23,699 rows and raised nothing.
    """
    import duckdb  # noqa: PLC0415

    try:
        # Eager here, unlike the pinned-dialect path: this fallback needs the
        # full row count up front to validate against _data_line_count below,
        # and it only runs for the rare legacy files that fail the pinned
        # read, so buffering the whole file is not the routine-case cost that
        # streaming _read_tsv avoids.
        batches = list(
            _read_tsv(path, chunk_size, {**duckdb_kwargs, **_UNQUOTED_READER_OVERRIDES})
        )
    except duckdb.Error:
        logger.exception("Unquoted read of edxorg TSV %s failed too.", file_url)
        return None

    rows = sum(batch.num_rows for batch in batches)
    expected = _data_line_count(path)
    if rows != expected:
        logger.error(
            "Unquoted read of edxorg TSV %s kept %s of %s lines; not loading it.",
            file_url,
            rows,
            expected,
        )
        return None
    return batches


@dlt.transformer(standalone=True)
def read_edxorg_tsv(
    items: Iterable[FileItemDict],
    chunk_size: int = 5000,
    **duckdb_kwargs: Any,
) -> Iterator[Any]:
    """Read edxorg TSVs, recovering legacy files and naming any it cannot read.

    Same work as ``dlt.sources.filesystem.read_csv_duckdb`` with
    ``use_pyarrow=True``, wrapped for four reasons.

    First, memory: each file is read from a local copy rather than a file
    object (see ``_local_copy``).

    Second, diagnosability. DuckDB names the file it was reading in an error,
    which is a temporary path here (and was an opaque
    ``DUCKDB_INTERNAL_OBJECTSTORE://e3d60147029d6cb5`` handle back when it was
    given a file object). Eleven Sentry issues (DAGSTER-1C and friends)
    reported a sniffing failure against a name that maps to nothing anyone can
    open. The S3 URL is right here; putting it in the exception is the
    difference between a reproducible bug and a shrug.

    Third, empty files. ``from_csv_auto`` cannot infer a dialect from zero
    bytes and fails with the same "not possible to automatically detect the CSV
    parsing dialect" message as a genuinely malformed file. An empty export is
    not an error -- there is simply nothing in it -- so it is skipped and logged
    rather than failing the whole table.

    Fourth, legacy unquoted dumps. One user-entered value starting with `"` is
    enough to make the pinned dialect unreadable. The pinned read is still tried
    first, because it is correct for everything the archive writes today; only
    a file it rejects is re-read unquoted, and kept only if no row was lost.

    Note that pinning the dialect does not remove the sniffer: DuckDB still runs
    it to find the header and column count.

    The pinned read is only retried unquoted before its first batch has been
    yielded. Priming the generator this way still catches every sniff failure
    (see ``_read_tsv``'s docstring for why those are guaranteed to raise
    before any row is produced) without letting a LATER duckdb.Error trigger
    the same fallback -- retrying then would re-read the whole file under a
    different dialect and splice it onto rows already sent downstream from
    the first attempt, corrupting the load with duplicated/inconsistently
    parsed data instead of recovering it.
    """
    import duckdb  # noqa: PLC0415

    for item in items:
        if not item.get("size_in_bytes"):
            logger.warning(
                "Skipping empty edxorg TSV %s -- nothing to read.", item["file_url"]
            )
            continue

        def _stamp(batch: Any, item: FileItemDict = item) -> Any:  # noqa: ANN401
            return add_file_metadata(
                batch,
                source_file=item["file_url"],
                modified_at=item.get("modification_date"),
            )

        with _local_copy(item) as path:
            reader = _read_tsv(path, chunk_size, duckdb_kwargs)
            try:
                first_batch = next(reader)
            except StopIteration:
                continue  # pinned dialect read the whole file; it just had no rows
            except duckdb.Error as error:
                logger.warning(
                    "Pinned dialect could not read edxorg TSV %s; retrying unquoted.",
                    item["file_url"],
                )
                unquoted = _read_unquoted_tsv(
                    path, item["file_url"], chunk_size, duckdb_kwargs
                )
                if unquoted is None:
                    msg = (
                        f"DuckDB could not read the edxorg TSV {item['file_url']} "
                        f"({item.get('size_in_bytes')} bytes): {error}"
                    )
                    raise EdxorgTSVUnreadableError(msg) from error
                for batch in unquoted:
                    yield _stamp(batch)
                continue

            yield _stamp(first_batch)
            try:
                for batch in reader:
                    yield _stamp(batch)
            except duckdb.Error as error:
                msg = (
                    f"DuckDB failed partway through the edxorg TSV {item['file_url']} "
                    f"({item.get('size_in_bytes')} bytes) after already yielding "
                    "rows read under the pinned dialect, so it cannot be safely "
                    f"retried unquoted: {error}"
                )
                raise EdxorgTSVUnreadableError(msg) from error


# dlt keys incremental state by "<parent resource>_<piped resource>", so this
# name is part of every table's saved cursor. It stays "filesystem" -- what
# dlt.sources.filesystem.filesystem was called -- because renaming it orphans
# the cursor main has been saving since #2443's wiring shipped: every table
# would re-list its landing zone from the beginning and, under append,
# re-insert every row it already holds. Verified by running both wirings
# against one pipeline: the old key is filesystem_raw__edxorg__s3__tables__X,
# the new one edxorg_files_raw__..., and run 3 re-read everything.
@dlt.resource(name="filesystem", primary_key="file_url", standalone=True)
def edxorg_files(
    bucket_url: str,
    file_glob: str,
    credentials: Any,
    budget_bytes: int = _DEFAULT_BUDGET_BYTES,
    modification_date: incremental[Any] = dlt.sources.incremental(  # noqa: B008
        "modification_date"
    ),
) -> Iterator[list[FileItemDict]]:
    """List one batch of unread TSVs, oldest first.

    ``budget_bytes`` caps the files this batch yields past the cursor's
    second. The cursor's own second is deliberately exempt and is NOT capped
    (see the boundary branch below), so a batch's true ceiling is the unread
    bytes in that one second plus ``budget_bytes`` plus, when the first unread
    file is larger than the whole budget, that file.

    This is where the budget has to live. A dlt transformer is invoked once
    per page, so a running total kept in ``read_edxorg_tsv`` restarts at zero
    for every file and never trips -- confirmed against the landing zone,
    where a 20 MB budget read all 3,336 certificates_generatedcertificate
    files. Worse, a transformer that did stop would stop only itself: the
    resource above it keeps yielding, and the incremental cursor advances over
    files nothing ever read. Not yielding a file is the only thing that keeps
    the cursor off it.

    Sorting by modification_date is what makes stopping early safe: everything
    left unyielded sorts after the cursor this batch saves. The caller re-runs
    the source until a batch comes back empty.

    ``dlt.sources.filesystem.filesystem`` is not reused because its budget
    would have to be enforced downstream of its own yields, which is the
    failure above.
    """
    from dlt.common.storages.fsspec_filesystem import glob_files  # noqa: PLC0415

    listed = sorted(
        glob_files(credentials, bucket_url, file_glob),
        key=lambda file_item: file_item["modification_date"],
    )
    cursor_value = modification_date.last_value
    batch_bytes = 0
    boundary_bytes = 0
    # "Definitely unread", not merely "unread": a boundary file may be a
    # re-listing of the file this batch resumes on, which dedups upstream of
    # the reader, so it cannot be counted as progress.
    yielded_definitely_unread = False

    for file_item in listed:
        modified_at = file_item["modification_date"]
        size = file_item["size_in_bytes"]

        if cursor_value is not None and modified_at < cursor_value:
            continue  # read by an earlier batch

        if cursor_value is not None and modified_at == cursor_value:
            # The boundary second. dlt's cursor boundary is inclusive, so the
            # file this batch resumes on is listed again and deduped against
            # the file_url hashes kept from last time; charging it to the
            # budget would let one already-read file (the largest export is
            # 14.5 GB) exhaust the batch before anything new is yielded, and
            # an empty batch reads as a drained backlog. S3 reports whole
            # seconds, so a file sharing this second may instead be unread,
            # which is why the whole group is yielded and left for dedup to
            # sort out. Measured across courseware_studentmodule's 58,378
            # files: the largest single second holds 14.48 GB, and only 8
            # seconds hold more than 4 GiB, so the group is small in practice.
            yield [FileItemDict(file_item, credentials)]
            boundary_bytes += size
            continue

        # Check before yielding, so the files past the boundary second come
        # to at most the budget rather than the budget plus whatever the file
        # that crossed the line happens to weigh. The flag keeps a file larger
        # than the entire budget from being skipped forever: it becomes a
        # batch of its own.
        if yielded_definitely_unread and batch_bytes + size > budget_bytes:
            logger.info(
                "Listed %s bytes of edxorg TSV for %s against a %s byte "
                "budget (%s more on the cursor boundary); ending this batch.",
                batch_bytes,
                file_glob,
                budget_bytes,
                boundary_bytes,
            )
            return

        # A page of one: the cursor advances over a page as a whole, so a
        # larger page would carry it past files this batch stops before.
        yield [FileItemDict(file_item, credentials)]
        yielded_definitely_unread = True
        batch_bytes += size


@dlt.source(name="edxorg_s3")
def edxorg_s3_source(
    tables: list[str] | None = None,
    bucket_url: str = _EDXORG_LANDING_BUCKET,
    table_format: config.TableFormat | None = None,
    budget_bytes: int = _DEFAULT_BUDGET_BYTES,
) -> Generator[Any]:
    """Load edxorg CSV/TSV data from S3, one resource per table.

    Uses AWS IAM auth automatically (``~/.aws/credentials`` locally; IRSA in
    K8s).

    Args:
        tables: Table names to load. The ``data_loading`` wrapper passes
            ``EDXORG_DB_TABLES``; an empty/None list yields no resources.
        bucket_url: S3 bucket URL containing the TSV files.
        table_format: ``native`` (parquet) or ``iceberg``; defaults to the active
            profile's table format.
        budget_bytes: How much source TSV one load may cover before the batch
            ends. The caller re-runs the source until a batch reads nothing,
            which is how the backlog is walked without holding a whole table's
            load in memory.
    """
    resolved_format = table_format or config.active_table_format()

    for table_name in tables or []:
        resource_name = f"raw__edxorg__s3__tables__{table_name}"
        # Match ONLY prod TSV files for this table; exclude edge staging files.
        file_glob = f"db_table/{table_name}/prod/**/*.tsv"

        # Create an s3fs filesystem WITHOUT explicit credentials.
        #
        # dlt's AwsCredentials.to_session_credentials() snapshots the live IRSA
        # RefreshableCredentials object as static strings and passes them to
        # s3fs.S3FileSystem(key=..., secret=..., token=...). Once s3fs holds
        # static strings there is no refresh path: when the STS token expires
        # (~1h) every subsequent GetObject fails with ExpiredToken.
        #
        # By constructing S3FileSystem with no explicit key/secret/token we
        # bypass dlt's credential snapshotting. aiobotocore then uses its own
        # credential chain which, for IRSA pods, wraps the result in
        # AioRefreshableCredentials that re-assume the role on expiry, so the
        # pipeline can run indefinitely.
        #
        # Do NOT pass extract_content=True: that reads the whole file into bytes
        # in one blocking request (can exceed a token lifetime for big tables),
        # and _local_copy would then copy those bytes back out of memory --
        # reinstating the whole-file-in-RAM read it exists to avoid. Leaving it
        # False lets item.open() stream chunk-by-chunk.
        fs = s3fs.S3FileSystem()

        # edxorg_files owns the modification_date cursor and the per-batch
        # byte budget; only files the cursor has not covered are processed,
        # and only until the budget is reached.
        files = edxorg_files(
            bucket_url=bucket_url,
            file_glob=file_glob,
            credentials=fs,
            budget_bytes=budget_bytes,
        )

        # Pipe filesystem items through read_edxorg_tsv, then rename and
        # configure via with_name() + apply_hints(). A @dlt.resource wrapper that
        # *returns* another DltResource would replace the outer resource and
        # discard its name/hints; applying hints on the pipe avoids that.
        yield (
            (files | read_edxorg_tsv(**_CSV_READER_OPTIONS))
            .with_name(resource_name)
            .apply_hints(
                table_name=resource_name,
                # Append, not merge, and this trades storage for a load that
                # can actually finish.
                #
                # What merge bought: row_hash is a sha256 over the original CSV
                # columns (edxorg_archive.py), so a match on (row_hash,
                # extracted_course_key) is a row whose content did not change
                # between two exports of a course. Merge UPDATED those in place
                # rather than inserting them, which is what kept re-exports
                # from multiplying the table -- courses are exported over and
                # over (543 of 1,647 courseware_studentmodule courses have 50+
                # exports of near-identical size), so append inserts an entire
                # export where merge inserted only its changed rows.
                #
                # What it cost: dlt drives pyiceberg's upsert at 1,000 rows per
                # Iceberg commit and holds the whole load in memory to do it,
                # which is a load that does not complete at this table's size.
                # The update half of the merge was also always a no-op, since a
                # matched row is identical; a record that DID change hashes
                # differently and was inserted as a second row regardless, so
                # merge never produced one row per business key either.
                #
                # The duplicates come out after the load instead:
                # `deduplicate_raw_table` in staging once this unit's
                # `raw_metadata_column` names _file_modified_at, and a
                # compaction pass over the raw layer. Until both exist, raw
                # holds every row of every export.
                write_disposition="append",
                # Kept as documentation of the grain (and read by the ingestion
                # inventory); append does not deduplicate on it. Composite
                # because row_hash covers only the original CSV columns, so
                # identical rows from different courses collide on row_hash
                # alone.
                primary_key=_EDXORG_PRIMARY_KEY,
                table_format=resolved_format,
                # All three nullable, overriding dlt's required default -- see
                # config.DLT_LOAD_ID_COLUMN. This source has no build_source()
                # to route through config.with_nullable_load_id, so it declares
                # them on the resource directly.
                columns={**config.DLT_LOAD_ID_COLUMN, **FILE_METADATA_COLUMNS},
            )
        )


# Bucket prefix is "edxorg" to preserve the existing
# s3://ol-data-lake-raw-<env>/edxorg destination path.
edxorg_s3_pipeline = config.pipeline_for("edxorg", pipeline_name="edxorg_s3")


def edxorg_s3_pipeline_for(table_name: str) -> dlt.Pipeline:
    """Return a per-table pipeline for concurrent per-table materialization.

    dlt pipelines keep a LOCAL working directory (extract/normalize staging,
    schema + state cache) keyed by ``pipeline_name``. Tables loaded through
    the shared ``edxorg_s3_pipeline`` singleton must run strictly
    sequentially -- two pipeline instances with the same name racing in
    separate OS processes corrupt each other's staging files (reproduced:
    concurrent runs sharing one pipeline_name fail with
    ``NormalizeJobFailed``/``FileNotFoundError`` on the shared staging dir).
    A distinct, STABLE per-table pipeline_name isolates each table's local
    state so tables can load concurrently. Still writes into the same
    ``s3://.../edxorg`` destination bucket and dataset as ``edxorg_s3_pipeline``
    -- only the local working-directory identity changes, not where data lands.

    NOTE: this pipeline_name must stay stable across deploys -- dlt keys the
    incremental ``modification_date`` cursor by pipeline_name + resource name,
    so renaming it resets that table's cursor and reprocesses the whole landing
    zone. Under the old merge disposition that was merely slow and expensive
    for one run; under append it re-inserts every file, so the duplicates last
    until staging dedup hides them and the compaction pass removes them.
    """
    return config.pipeline_for("edxorg", pipeline_name=f"edxorg_s3__{table_name}")
