"""EdX.org S3 CSV/TSV data ingestion via dlt.

Loads TSV files from S3 that are generated by the ``edxorg_archive`` asset.
These files contain database-table exports from edX.org courses.

S3 structure::

    s3://.../edxorg-raw-data/edxorg/raw_data/db_table/{table}/{system}/{course}/{hash}.tsv

The set of tables to load is supplied by the caller (the ``data_loading``
Dagster wrapper passes ``EDXORG_DB_TABLES`` from ``ol_orchestrate``); this source
stays pure dlt and owns no Dagster/orchestration dependencies.

Run standalone:
    DLT_PROFILE=dev python -m ol_dlt.sources.edxorg_s3
"""

import logging
from collections.abc import Generator
from typing import Any

import dlt
import pyarrow as pa
import s3fs
from dlt.sources import incremental
from dlt.sources.filesystem import filesystem, read_csv_duckdb

from ol_dlt import config

logger = logging.getLogger(__name__)

# Source bucket (the edxorg archive landing zone). This is always the production
# landing zone regardless of the active profile — it is where TSVs are read FROM,
# not where data is written TO.
_EDXORG_LANDING_BUCKET = (
    "s3://ol-data-lake-landing-zone-production/edxorg-raw-data/edxorg/raw_data/"
)

_EDXORG_PRIMARY_KEY = ["row_hash", "extracted_course_key"]


def _make_deduplicator():  # noqa: ANN202
    """Return a stateful per-run deduplication function for use with add_map.

    Tracks seen (row_hash, extracted_course_key) pairs and drops rows whose key
    was already seen earlier in the same extraction run. Scoped per call, so each
    ``edxorg_s3_source()`` invocation starts with an empty seen-set.

    pyiceberg's upsert raises ValueError when the source DataFrame contains
    duplicate join-key rows, even if those rows are identical. This happens when
    multiple TSV files from overlapping archive runs are extracted in one dlt run
    and combined into a single normalised parquet file.
    """
    seen: set[tuple[str | None, ...]] = set()

    def _dedup(item: object) -> object:
        if not isinstance(item, (pa.Table, pa.RecordBatch)):
            return item

        tbl = item if isinstance(item, pa.Table) else pa.Table.from_batches([item])

        # Require ALL primary key columns to be present. Partial-key
        # deduplication (e.g. on row_hash alone) would silently drop valid rows
        # because row_hash is not course-unique on its own.
        if not all(k in tbl.schema.names for k in _EDXORG_PRIMARY_KEY):
            return tbl

        key_cols = [tbl.column(k).to_pylist() for k in _EDXORG_PRIMARY_KEY]

        keep = []
        for key in zip(*key_cols, strict=True):
            keep.append(key not in seen)
            seen.add(key)

        if all(keep):
            return tbl
        if not any(keep):
            # Return an empty table (same schema) rather than None. The add_map
            # docs say to use add_filter for dropping records; returning None
            # from add_map is undefined and may propagate as data.
            return tbl.slice(0, 0)

        return tbl.filter(pa.array(keep, type=pa.bool_()))

    return _dedup


@dlt.source(name="edxorg_s3")
def edxorg_s3_source(
    tables: list[str] | None = None,
    bucket_url: str = _EDXORG_LANDING_BUCKET,
    table_format: config.TableFormat | None = None,
) -> Generator[Any]:
    """Load edxorg CSV/TSV data from S3, one resource per table.

    Uses AWS IAM auth automatically (``~/.aws/credentials`` locally; IRSA in
    K8s).

    Args:
        tables: Table names to load. The ``data_loading`` wrapper passes
            ``EDXORG_DB_TABLES``; an empty/None list yields no resources.
        bucket_url: S3 bucket URL containing the TSV files.
        table_format: ``native`` (parquet) or ``iceberg``; defaults to the active
            profile's table format.
    """
    resolved_format = table_format or config.active_table_format()

    for table_name in tables or []:
        resource_name = f"raw__edxorg__s3__tables__{table_name}"
        # Match ONLY prod TSV files for this table; exclude edge staging files.
        file_glob = f"db_table/{table_name}/prod/**/*.tsv"

        # Create an s3fs filesystem WITHOUT explicit credentials.
        #
        # dlt's AwsCredentials.to_session_credentials() snapshots the live IRSA
        # RefreshableCredentials object as static strings and passes them to
        # s3fs.S3FileSystem(key=..., secret=..., token=...). Once s3fs holds
        # static strings there is no refresh path: when the STS token expires
        # (~1h) every subsequent GetObject fails with ExpiredToken.
        #
        # By constructing S3FileSystem with no explicit key/secret/token we
        # bypass dlt's credential snapshotting. aiobotocore then uses its own
        # credential chain which, for IRSA pods, wraps the result in
        # AioRefreshableCredentials that re-assume the role on expiry, so the
        # pipeline can run indefinitely.
        #
        # Do NOT pass extract_content=True: that reads the whole file into bytes
        # in one blocking request (can exceed a token lifetime for big tables).
        # Leaving it False lets read_csv_duckdb stream chunk-by-chunk.
        fs = s3fs.S3FileSystem()

        # Pass incremental directly to filesystem() so dlt tracks the
        # modification_date cursor per-resource; only files newer than the last
        # successful run's cursor are processed.
        files = filesystem(
            bucket_url=bucket_url,
            file_glob=file_glob,
            credentials=fs,
            incremental=incremental("modification_date"),
        )

        # Pipe filesystem items through read_csv_duckdb, then rename and
        # configure via with_name() + apply_hints(). A @dlt.resource wrapper that
        # *returns* another DltResource would replace the outer resource and
        # discard its name/hints; applying hints on the pipe avoids that.
        yield (
            (
                files
                | read_csv_duckdb(
                    use_pyarrow=True,
                    delimiter="\t",  # TSV files use tabs
                    ignore_errors=True,
                    # Force all columns to VARCHAR to prevent pyarrow schema
                    # mismatches across files (e.g. TIMESTAMP vs VARCHAR for a
                    # column that is empty in some files). dbt casts downstream.
                    all_varchar=True,
                )
            )
            .with_name(resource_name)
            # Drop rows whose (row_hash, extracted_course_key) was already seen
            # earlier in this run (see _make_deduplicator docstring).
            .add_map(_make_deduplicator())
            # Composite key: row_hash is computed from only the original CSV
            # columns, so identical rows from different courses would collide on
            # row_hash alone.
            .apply_hints(
                table_name=resource_name,
                write_disposition="merge",
                primary_key=_EDXORG_PRIMARY_KEY,
                table_format=resolved_format,
            )
        )


# Bucket prefix is "edxorg" to preserve the existing
# s3://ol-data-lake-raw-<env>/edxorg destination path.
edxorg_s3_pipeline = config.pipeline_for("edxorg", pipeline_name="edxorg_s3")


def edxorg_s3_pipeline_for(table_name: str) -> dlt.Pipeline:
    """Return a per-table pipeline for concurrent per-table materialization.

    dlt pipelines keep a LOCAL working directory (extract/normalize staging,
    schema + state cache) keyed by ``pipeline_name``. Tables loaded through
    the shared ``edxorg_s3_pipeline`` singleton must run strictly
    sequentially -- two pipeline instances with the same name racing in
    separate OS processes corrupt each other's staging files (reproduced:
    concurrent runs sharing one pipeline_name fail with
    ``NormalizeJobFailed``/``FileNotFoundError`` on the shared staging dir).
    A distinct, STABLE per-table pipeline_name isolates each table's local
    state so tables can load concurrently. Still writes into the same
    ``s3://.../edxorg`` destination bucket and dataset as ``edxorg_s3_pipeline``
    -- only the local working-directory identity changes, not where data lands.

    NOTE: this pipeline_name must stay stable across deploys -- dlt keys the
    incremental ``modification_date`` cursor by pipeline_name + resource name,
    so renaming it resets that table's cursor and triggers a full S3 reprocess
    on the next run (safe -- merge + primary_key dedup makes reprocessing
    idempotent -- but slower and more expensive for that one run).
    """
    return config.pipeline_for("edxorg", pipeline_name=f"edxorg_s3__{table_name}")
