"""EdX.org S3 CSV/TSV data ingestion via dlt.

Loads TSV files from S3 that are generated by the ``edxorg_archive`` asset.
These files contain database-table exports from edX.org courses.

S3 structure::

    s3://.../edxorg-raw-data/edxorg/raw_data/db_table/{table}/{system}/{course}/{hash}.tsv

The set of tables to load is supplied by the caller (the ``data_loading``
Dagster wrapper passes ``EDXORG_DB_TABLES`` from ``ol_orchestrate``); this source
stays pure dlt and owns no Dagster/orchestration dependencies.

Run standalone:
    DLT_PROFILE=dev python -m ol_dlt.sources.edxorg_s3
"""

import hashlib
import logging
from collections.abc import Generator, Iterable, Iterator
from typing import Any

import dlt
import pyarrow as pa
import s3fs
from dlt.sources import incremental
from dlt.sources.filesystem import FileItemDict, filesystem
from dlt.sources.filesystem.helpers import fetch_arrow

from ol_dlt import config

logger = logging.getLogger(__name__)

# Source bucket (the edxorg archive landing zone). This is always the production
# landing zone regardless of the active profile — it is where TSVs are read FROM,
# not where data is written TO.
_EDXORG_LANDING_BUCKET = (
    "s3://ol-data-lake-landing-zone-production/edxorg-raw-data/edxorg/raw_data/"
)

_EDXORG_PRIMARY_KEY = ["row_hash", "extracted_course_key"]

# Options handed to DuckDB's CSV reader for every edxorg TSV.
_CSV_READER_OPTIONS: dict[str, Any] = {
    "delimiter": "\t",  # TSV files use tabs
    "ignore_errors": True,
    # These are dumps of user-entered free text (auth_userprofile.bio, .goals,
    # .mailing_address and friends), so a field occasionally carries a bare CR
    # or a CRLF while the rest of the file is LF-terminated. DuckDB's strict
    # mode treats mixed newlines as a dialect violation, and the dialect sniffer
    # runs BEFORE ignore_errors can suppress anything -- so one stray CR kills
    # the entire resource with "It was not possible to automatically detect the
    # CSV parsing dialect" instead of skipping the one bad row. Relaxing strict
    # mode lets the sniffer settle on a dialect and routes the malformed rows to
    # ignore_errors, where they belong. Clean LF and clean CRLF files parse
    # identically either way.
    #
    # Deliberately NOT setting null_padding: on a row with more fields than the
    # header it would materialise synthetic `columnN` columns, which vary per
    # file and would churn the destination schema.
    "strict_mode": False,
    # Pin the quote/escape dialect instead of letting the sniffer guess it.
    # The upstream edxorg_archive asset writes these files with polars'
    # quote_style="necessary", which uses RFC-4180 doubling -- an embedded `"`
    # is written as `""` inside a quoted field. Left to its own devices the
    # sniffer picks a quote/escape pair that does NOT undouble it, so
    # `he said "hi"` silently reads back as `he said ""hi""`. Setting escapechar
    # to the quote character makes the undoubling explicit.
    #
    # This is also correct for the older, entirely unquoted files still sitting
    # in the landing zone: with nothing quoted there is nothing to unescape, and
    # they parse identically with or without these pinned.
    "quotechar": '"',
    "escapechar": '"',
    # Force all columns to VARCHAR to prevent pyarrow schema mismatches across
    # files (e.g. TIMESTAMP vs VARCHAR for a column that is empty in some
    # files). dbt casts downstream.
    "all_varchar": True,
}


class EdxorgTSVUnreadableError(Exception):
    """DuckDB could not read one edxorg TSV, named in the message."""


@dlt.transformer(standalone=True)
def read_edxorg_tsv(
    items: Iterable[FileItemDict],
    chunk_size: int = 5000,
    **duckdb_kwargs: Any,
) -> Iterator[Any]:
    """Read edxorg TSVs, naming the file when DuckDB cannot read one.

    Same work as ``dlt.sources.filesystem.read_csv_duckdb`` with
    ``use_pyarrow=True``, wrapped for two reasons.

    First, diagnosability. ``duckdb.from_csv_auto`` is handed an open file
    object, so the file it names in an error is DuckDB's internal handle --
    ``DUCKDB_INTERNAL_OBJECTSTORE://e3d60147029d6cb5``. Eleven Sentry issues
    (DAGSTER-1C and friends) reported a sniffing failure against a content hash
    that maps to nothing anyone can open. The S3 URL is right here; putting it in
    the exception is the difference between a reproducible bug and a shrug.

    Second, empty files. ``from_csv_auto`` cannot infer a dialect from zero
    bytes and fails with the same "not possible to automatically detect the CSV
    parsing dialect" message as a genuinely malformed file. An empty export is
    not an error -- there is simply nothing in it -- so it is skipped and logged
    rather than failing the whole table.

    Note that pinning the dialect does not remove the sniffer: DuckDB still runs
    it to find the header and column count. The delimiter, quote and escape are
    already pinned in ``_CSV_READER_OPTIONS`` and these failures happened anyway.
    """
    import duckdb  # noqa: PLC0415

    for item in items:
        if not item.get("size_in_bytes"):
            logger.warning(
                "Skipping empty edxorg TSV %s -- nothing to read.", item["file_url"]
            )
            continue

        with item.open() as file_handle:
            try:
                file_data = duckdb.from_csv_auto(file_handle, **duckdb_kwargs)
                batches = list(fetch_arrow(file_data, chunk_size))
            except duckdb.Error as error:
                msg = (
                    f"DuckDB could not read the edxorg TSV {item['file_url']} "
                    f"({item.get('size_in_bytes')} bytes): {error}"
                )
                raise EdxorgTSVUnreadableError(msg) from error
        yield from batches


def _make_deduplicator():  # noqa: ANN202
    """Return a stateful per-run deduplication function for use with add_map.

    Tracks seen (row_hash, extracted_course_key) pairs and drops rows whose key
    was already seen earlier in the same extraction run. Scoped per call, so each
    ``edxorg_s3_source()`` invocation starts with an empty seen-set.

    pyiceberg's upsert raises ValueError when the source DataFrame contains
    duplicate join-key rows, even if those rows are identical. This happens when
    multiple TSV files from overlapping archive runs are extracted in one dlt run
    and combined into a single normalised parquet file.

    ``seen`` holds one entry per row for the entire table's extraction, so for
    high-row-count/high-file-count tables (e.g. auth_user, courseware_studentmodule,
    dumped per-course across thousands of files) it dominates the op's peak RSS.
    Storing a fixed-size digest instead of the raw (row_hash, extracted_course_key)
    string tuple cuts per-entry overhead well below the tuple-of-two-strings form
    (each of which carries its own PyObject header), at the cost of dedup becoming
    probabilistic rather than exact: two distinct keys could in principle hash to
    the same 128-bit digest and get treated as duplicates. blake2b at this digest
    size makes that collision probability cryptographically negligible (a random
    128-bit hash needs on the order of 2**64 distinct keys before a collision
    becomes likely -- far beyond any realistic table here), so this is not treated
    as a real risk in practice, but it is not literally identical semantics to the
    original exact-comparison set.
    """
    seen: set[bytes] = set()

    def _encode_key_part(part: str | None) -> bytes:
        """Encode one primary-key component unambiguously as bytes.

        Length-prefixing (rather than joining with a separator) means no
        separator choice can collide with separator-like bytes inside the
        data, and tagging ``None`` with its own marker (rather than folding
        it into ``""``) keeps a NULL primary-key value distinct from an
        empty-string one, matching the original tuple-based set's semantics.
        """
        if part is None:
            return b"\x00"
        encoded = part.encode()
        return b"\x01" + len(encoded).to_bytes(4, "big") + encoded

    def _dedup(item: object) -> object:
        if not isinstance(item, (pa.Table, pa.RecordBatch)):
            return item

        tbl = item if isinstance(item, pa.Table) else pa.Table.from_batches([item])

        # Require ALL primary key columns to be present. Partial-key
        # deduplication (e.g. on row_hash alone) would silently drop valid rows
        # because row_hash is not course-unique on its own.
        if not all(k in tbl.schema.names for k in _EDXORG_PRIMARY_KEY):
            return tbl

        key_cols = [tbl.column(k).to_pylist() for k in _EDXORG_PRIMARY_KEY]

        keep = []
        for key in zip(*key_cols, strict=True):
            digest = hashlib.blake2b(
                b"".join(_encode_key_part(part) for part in key),
                digest_size=16,
            ).digest()
            keep.append(digest not in seen)
            seen.add(digest)

        if all(keep):
            return tbl
        if not any(keep):
            # Return an empty table (same schema) rather than None. The add_map
            # docs say to use add_filter for dropping records; returning None
            # from add_map is undefined and may propagate as data.
            return tbl.slice(0, 0)

        return tbl.filter(pa.array(keep, type=pa.bool_()))

    return _dedup


@dlt.source(name="edxorg_s3")
def edxorg_s3_source(
    tables: list[str] | None = None,
    bucket_url: str = _EDXORG_LANDING_BUCKET,
    table_format: config.TableFormat | None = None,
) -> Generator[Any]:
    """Load edxorg CSV/TSV data from S3, one resource per table.

    Uses AWS IAM auth automatically (``~/.aws/credentials`` locally; IRSA in
    K8s).

    Args:
        tables: Table names to load. The ``data_loading`` wrapper passes
            ``EDXORG_DB_TABLES``; an empty/None list yields no resources.
        bucket_url: S3 bucket URL containing the TSV files.
        table_format: ``native`` (parquet) or ``iceberg``; defaults to the active
            profile's table format.
    """
    resolved_format = table_format or config.active_table_format()

    for table_name in tables or []:
        resource_name = f"raw__edxorg__s3__tables__{table_name}"
        # Match ONLY prod TSV files for this table; exclude edge staging files.
        file_glob = f"db_table/{table_name}/prod/**/*.tsv"

        # Create an s3fs filesystem WITHOUT explicit credentials.
        #
        # dlt's AwsCredentials.to_session_credentials() snapshots the live IRSA
        # RefreshableCredentials object as static strings and passes them to
        # s3fs.S3FileSystem(key=..., secret=..., token=...). Once s3fs holds
        # static strings there is no refresh path: when the STS token expires
        # (~1h) every subsequent GetObject fails with ExpiredToken.
        #
        # By constructing S3FileSystem with no explicit key/secret/token we
        # bypass dlt's credential snapshotting. aiobotocore then uses its own
        # credential chain which, for IRSA pods, wraps the result in
        # AioRefreshableCredentials that re-assume the role on expiry, so the
        # pipeline can run indefinitely.
        #
        # Do NOT pass extract_content=True: that reads the whole file into bytes
        # in one blocking request (can exceed a token lifetime for big tables).
        # Leaving it False lets read_csv_duckdb stream chunk-by-chunk.
        fs = s3fs.S3FileSystem()

        # Pass incremental directly to filesystem() so dlt tracks the
        # modification_date cursor per-resource; only files newer than the last
        # successful run's cursor are processed.
        files = filesystem(
            bucket_url=bucket_url,
            file_glob=file_glob,
            credentials=fs,
            incremental=incremental("modification_date"),
        )

        # Pipe filesystem items through read_csv_duckdb, then rename and
        # configure via with_name() + apply_hints(). A @dlt.resource wrapper that
        # *returns* another DltResource would replace the outer resource and
        # discard its name/hints; applying hints on the pipe avoids that.
        yield (
            (files | read_edxorg_tsv(**_CSV_READER_OPTIONS))
            .with_name(resource_name)
            # Drop rows whose (row_hash, extracted_course_key) was already seen
            # earlier in this run (see _make_deduplicator docstring).
            .add_map(_make_deduplicator())
            # Composite key: row_hash is computed from only the original CSV
            # columns, so identical rows from different courses would collide on
            # row_hash alone.
            .apply_hints(
                table_name=resource_name,
                write_disposition="merge",
                primary_key=_EDXORG_PRIMARY_KEY,
                table_format=resolved_format,
            )
        )


# Bucket prefix is "edxorg" to preserve the existing
# s3://ol-data-lake-raw-<env>/edxorg destination path.
edxorg_s3_pipeline = config.pipeline_for("edxorg", pipeline_name="edxorg_s3")


def edxorg_s3_pipeline_for(table_name: str) -> dlt.Pipeline:
    """Return a per-table pipeline for concurrent per-table materialization.

    dlt pipelines keep a LOCAL working directory (extract/normalize staging,
    schema + state cache) keyed by ``pipeline_name``. Tables loaded through
    the shared ``edxorg_s3_pipeline`` singleton must run strictly
    sequentially -- two pipeline instances with the same name racing in
    separate OS processes corrupt each other's staging files (reproduced:
    concurrent runs sharing one pipeline_name fail with
    ``NormalizeJobFailed``/``FileNotFoundError`` on the shared staging dir).
    A distinct, STABLE per-table pipeline_name isolates each table's local
    state so tables can load concurrently. Still writes into the same
    ``s3://.../edxorg`` destination bucket and dataset as ``edxorg_s3_pipeline``
    -- only the local working-directory identity changes, not where data lands.

    NOTE: this pipeline_name must stay stable across deploys -- dlt keys the
    incremental ``modification_date`` cursor by pipeline_name + resource name,
    so renaming it resets that table's cursor and triggers a full S3 reprocess
    on the next run (safe -- merge + primary_key dedup makes reprocessing
    idempotent -- but slower and more expensive for that one run).
    """
    return config.pipeline_for("edxorg", pipeline_name=f"edxorg_s3__{table_name}")
