"""
EdX.org S3 CSV/TSV data ingestion via dlt.

This module loads TSV files from S3 that are generated by the edxorg_archive.py
asset. These files contain database table exports from edX.org courses.

S3 Structure:
s3://ol-data-lake-landing-zone-production/edxorg-raw-data/edxorg/raw_data/db_table/{table_name}/{source_system}/{course_id}/{hash}.tsv

Tables include:
- auth_user, auth_userprofile
- student_courseenrollment, courseware_studentmodule
- certificates_generatedcertificate
- submissions_*, assessment_*
- And many more...

Usage (standalone):
    # Local development (default - writes to .dlt/data/)
    python -m data_loading.defs.edxorg_s3_ingest.loads

    # Production (writes to S3)
    DAGSTER_ENVIRONMENT=production python -m data_loading.defs.edxorg_s3_ingest.loads
"""

import logging
import os
from pathlib import Path

import dlt
import pyarrow as pa
import s3fs
from dlt.sources import incremental
from dlt.sources.filesystem import filesystem, read_csv_duckdb
from ol_orchestrate.lib.constants import EDXORG_DB_TABLES

logger = logging.getLogger(__name__)

_EDXORG_PRIMARY_KEY = ["row_hash", "extracted_course_key"]


def _make_deduplicator():
    """
    Return a stateful per-run deduplication function for use with add_map.

    Tracks seen (row_hash, extracted_course_key) pairs and drops rows whose
    key was already seen earlier in the same extraction run.  Scoped per
    call, so each edxorg_s3_source() invocation (one table, one pipeline run)
    starts with an empty seen-set.

    pyiceberg's upsert raises ValueError when the source DataFrame contains
    duplicate join-key rows, even if those rows are identical.  This happens
    when multiple TSV files from overlapping archive runs are extracted in one
    dlt run and combined into a single normalised parquet file.
    """
    seen: set[tuple[str | None, ...]] = set()

    def _dedup(item: object) -> object:
        if not isinstance(item, (pa.Table, pa.RecordBatch)):
            return item

        tbl = item if isinstance(item, pa.Table) else pa.Table.from_batches([item])

        # Require ALL primary key columns to be present.  Partial-key
        # deduplication (e.g. on row_hash alone) would silently drop valid rows
        # because row_hash is not course-unique on its own.
        if not all(k in tbl.schema.names for k in _EDXORG_PRIMARY_KEY):
            return tbl

        key_cols = [tbl.column(k).to_pylist() for k in _EDXORG_PRIMARY_KEY]

        keep = []
        for key in zip(*key_cols):
            keep.append(key not in seen)
            seen.add(key)

        if all(keep):
            return tbl
        if not any(keep):
            # Return an empty table (same schema) rather than None.
            # The add_map docs say to use add_filter for dropping records;
            # returning None from add_map is undefined and may propagate as data.
            return tbl.slice(0, 0)

        return tbl.filter(pa.array(keep, type=pa.bool_()))

    return _dedup


# Set dlt project directory to the data_loading project root
# This ensures .dlt/config.toml is found when running from repo root
DLT_PROJECT_DIR = Path(__file__).parent.parent.parent.parent
if DLT_PROJECT_DIR.exists():
    os.environ.setdefault("DLT_PROJECT_DIR", str(DLT_PROJECT_DIR))


@dlt.source
def edxorg_s3_source(
    bucket_url: str = dlt.config.value,
    tables: list[str] | None = None,
    table_format: str = "parquet",  # "parquet" for local, "iceberg" for QA/prod
):
    """
    Load edxorg CSV/TSV data from S3.

    Uses AWS IAM authentication automatically:
    - Local development: Uses ~/.aws/credentials
    - Production/K8s: Uses IRSA (IAM Roles for Service Accounts)

    Args:
        bucket_url: S3 bucket URL containing TSV files
        tables: Optional list of specific tables to load (loads all if None)
        table_format: "parquet" for local dev, "iceberg" for QA/production

    Yields:
        dlt resources for each table type found in S3
    """

    # Filter to requested tables if specified
    tables_to_load = tables if tables is not None else EDXORG_DB_TABLES

    for table_name in tables_to_load:
        resource_name = f"raw__edxorg__s3__tables__{table_name}"
        # Pattern to match ONLY prod TSV files for this table
        # Matches: db_table/{table_name}/prod/*/*.tsv
        # Excludes: db_table/{table_name}/edge/*/*.tsv (edge staging files)
        file_glob = f"db_table/{table_name}/prod/**/*.tsv"

        # Create an s3fs filesystem WITHOUT explicit credentials.
        #
        # dlt's AwsCredentials.to_session_credentials() calls
        # get_frozen_credentials(), which snapshots the live IRSA
        # RefreshableCredentials object as static strings and passes
        # them to s3fs.S3FileSystem(key=..., secret=..., token=...).
        # Once s3fs holds explicit static strings there is no refresh
        # path: when the STS session token expires (~1 hour by default)
        # every subsequent GetObject call fails with ExpiredToken.
        #
        # By constructing S3FileSystem with no explicit key/secret/token
        # we bypass dlt's credential snapshotting entirely.  aiobotocore
        # then uses its own credential chain which, for IRSA pods, invokes
        # AioAssumeRoleWithWebIdentityFetcher and wraps the result in
        # AioRefreshableCredentials.  Those credentials automatically call
        # AssumeRoleWithWebIdentity again whenever the token expires, so
        # the pipeline can run indefinitely without hitting ExpiredToken.
        #
        # dlt's filesystem() source accepts an AbstractFileSystem instance
        # as its `credentials` parameter and uses it directly, skipping
        # its own credential-dispatch logic.
        #
        # Do NOT pass extract_content=True.  That flag reads the entire
        # file into Python bytes in a single blocking request before
        # passing it to read_csv_duckdb, which can itself exceed a token
        # lifetime for very large tables.  Leaving it False lets
        # read_csv_duckdb stream the content chunk-by-chunk via PyArrow.
        fs = s3fs.S3FileSystem()

        # Pass incremental directly to filesystem() so dlt tracks the
        # modification_date cursor per-resource.  Only files newer than
        # the cursor from the last successful run are processed.
        files = filesystem(
            bucket_url=bucket_url,
            file_glob=file_glob,
            credentials=fs,
            incremental=incremental("modification_date"),
        )

        # Pipe filesystem items through read_csv_duckdb, then rename and
        # configure the resulting resource.  Using with_name() + apply_hints()
        # is required here: a @dlt.resource wrapper that *returns* another
        # DltResource causes dlt to replace the outer resource entirely,
        # discarding its name, write_disposition, primary_key, and
        # table_format hints.  The resulting writes land under the
        # transformer's own name ("read_csv_duckdb"), making schema and job
        # lookups fail.  Applying hints directly on the pipe avoids this.
        yield (
            (
                files
                | read_csv_duckdb(
                    use_pyarrow=True,
                    delimiter="\t",  # TSV files use tabs
                    ignore_errors=True,
                    # Force all columns to VARCHAR to prevent pyarrow schema mismatches.
                    # This occurs when DuckDB infers different types for the same column
                    # across files (e.g., TIMESTAMP vs. VARCHAR for columns that are
                    # empty in some files). Downstream dbt models handle type casting.
                    all_varchar=True,
                )
            )
            .with_name(resource_name)
            # Drop rows whose (row_hash, extracted_course_key) was already seen earlier
            # in this extraction run.  Multiple TSV files from overlapping archive runs
            # can carry the same logical row; dlt's normaliser combines them into one
            # parquet file, and pyiceberg's upsert raises ValueError on duplicate
            # join-key rows in the source DataFrame.
            .add_map(_make_deduplicator())
            # All edxorg TSV exports include a row_hash column. Use a composite key
            # with extracted_course_key because row_hash is computed from only the
            # original CSV columns (excluding the extracted_* fields added during
            # archive processing), so identical rows from different courses would
            # otherwise collide on row_hash alone.
            .apply_hints(
                table_name=resource_name,
                write_disposition="merge",
                primary_key=_EDXORG_PRIMARY_KEY,
                table_format=table_format,
            )
        )


# Determine environment and destination
# Use DAGSTER_ENVIRONMENT to determine destination and Glue database
dagster_env: str = os.getenv("DAGSTER_ENVIRONMENT", "dev")

# Map DAGSTER_ENVIRONMENT to destination config
# dev/ci -> local filesystem (Parquet, no Iceberg, no Glue)
# qa -> filesystem + Iceberg (S3 + ol_warehouse_qa_raw Glue database)
# production -> filesystem + Iceberg (S3 + ol_warehouse_production_raw Glue database)
table_format = "iceberg" if dagster_env in ("qa", "production") else "parquet"
if dagster_env in ("qa", "production"):
    destination_env = dagster_env
    dataset_name = f"ol_warehouse_{dagster_env}_raw"
else:
    # dev, ci, or any other value uses local
    destination_env = "local"
    dataset_name = "edxorg_s3_local"

# Create source instance with appropriate table format
# dlt resolves config from .dlt/config.toml at runtime
edxorg_s3_source_instance = edxorg_s3_source(
    table_format=table_format,
)

# Rename config sections to match dlt's named destination pattern
# For named destinations, dlt looks for [destination.<name>] with destination_type set

# Update config.toml structure:
# - [destination.local] with destination_type="filesystem"
# - [destination.qa] with destination_type="filesystem"
# - [destination.production] with destination_type="filesystem"

# Create pipeline with environment-specific named destination
edxorg_s3_pipeline = dlt.pipeline(
    pipeline_name="edxorg_s3",
    destination=destination_env,  # References [destination.<env>] in config.toml
    dataset_name=dataset_name,
    progress="log",
)


def run_pipeline(tables: list[str] | None = None):
    """
    Execute the edxorg S3 pipeline.

    Args:
        tables: Optional list of specific tables to load.
                If None, loads all tables (can be slow!).
                Example: ["auth_user", "student_courseenrollment"]
    """
    logger.info("Running edxorg S3 pipeline with destination: %s", destination_env)

    if tables:
        logger.info("Loading specific tables: %s", ", ".join(tables))
        source = edxorg_s3_source(tables=tables, table_format=table_format)
    else:
        logger.info("Loading all available tables (this may take a while)")
        source = edxorg_s3_source_instance

    load_info = edxorg_s3_pipeline.run(
        source,
        loader_file_format="parquet",
    )
    logger.info("Pipeline completed: %s", load_info)

    return load_info


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    # For testing, only load a small subset of tables
    test_tables = ["auth_user", "student_courseenrollment"]

    logger.info("Running with test tables for faster execution.")
    logger.info("To load all tables, call run_pipeline(tables=None)")

    run_pipeline(tables=test_tables)
