---
# Build context is set to repository root to access packages/ol-orchestrate-lib
directory: ../..
# The Dockerfile is located in the edxorg directory
dockerfile: dg_projects/edxorg/Dockerfile
registry: mitodl/dagster-edxorg
