---
# Build context is set to repository root to access packages/ol-orchestrate-lib
directory: ../..
# The Dockerfile is located in the canvas directory
dockerfile: dg_projects/canvas/Dockerfile
registry: mitodl/dagster-canvas
